/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */

export interface BillingAccountUpdate {
  /** @maxLength 255 */
  name?: string;
  /** @maxLength 255 */
  legal_name?: string;
  /** @maxLength 255 */
  email?: string;
  /** @maxLength 255 */
  address_line1?: string;
  /** @maxLength 255 */
  address_line2?: string;
  /** @maxLength 128 */
  address_city?: string;
  /** @maxLength 128 */
  address_state?: string;
  /** @maxLength 32 */
  address_postal_code?: string;
  /**
   * @minLength 2
   * @maxLength 2
   */
  address_country?: string;
  /** @maxLength 64 */
  tax_id?: string;
}
