/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import type { CancellationItemBillingType } from "./cancellationItemBillingType.js";
import type { CancellationItemStatus } from "./cancellationItemStatus.js";
import type { Money } from "./money.js";

/**
 * One subscription of the cancellation.
 */
export interface CancellationItem {
  /** The cancellation request of this subscription, the same as `Subscription.cancellation_request.id`. */
  id: string;
  subscription_id: string;
  plan_id: string;
  plan_name: string;
  /**
   * How the subscription is paid for. Only a `prepaid` subscription renews automatically; creating
   * the cancellation turned that off, and withdrawing the cancellation leaves it off.
   */
  billing_type: CancellationItemBillingType;
  status: CancellationItemStatus;
  release_started_at?: string;
  /** When the service ended, as confirmed by the service that provides it. */
  effective_at?: string;
  /** Present with `completed`. The part of the refund returned to the account balance. */
  balance_amount?: Money;
  /** Present with `completed`. The part restored to the credit grants that paid. */
  credit_amount?: Money;
  /** Present with `completed`. The part returned to the payment method it was paid with. */
  gateway_amount?: Money;
}
