/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import type { Money } from "./money.js";

export interface CheckoutOrderRequest {
  /**
   * The code to apply, evaluated again at confirmation. Omit to select an applicable account
   * discount. On an already confirmed checkout, omission retains the recorded discount.
   * @minLength 1
   * @maxLength 64
   */
  promotion_code?: string;
  /**
   * Quote.total in the order's currency, after discounts and tax but before applying credit
   * grants or balance. Omit to skip the amount comparison; an explicit zero is compared.
   * A different total fails with BILLING_AMOUNT_CHANGED. Must be a non-negative decimal
   * string; empty strings, null, JSON numbers, signs and exponent notation are rejected.
   */
  expected_amount?: Money & string;
}
