/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import type { Applicability } from "./applicability.js";
import type { DiscountStatus } from "./discountStatus.js";
import type { DiscountType } from "./discountType.js";
import type { Money } from "./money.js";

/**
 * A coupon held on this account. It applies at checkout without a code.
 */
export interface Discount {
  min_amount?: string;
  billing_account_id?: number;
  coupon_id: string;
  promotion_code_id?: string;
  status: DiscountStatus;
  revoked_at?: string;
  type: DiscountType;
  recurring?: boolean;
  /** @minimum 1 */
  recurring_cycles?: number;
  id: string;
  name?: string;
  /** For a percentage discount, out of one hundred. */
  percent_off?: string;
  amount?: Money;
  /** Caps a percentage discount. */
  max_discount?: Money;
  currency?: string;
  /**
   * What it may be used for. Absent means it applies to anything on the account,
   * including setup fees and traffic.
   */
  applies_to: Applicability;
  /** Restricted to your first purchase of anything it applies to. */
  first_purchase_only?: boolean;
  started_at?: string;
  /** @nullable */
  ended_at?: string | null;
}
