/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import type { ObjectIdentity } from "./objectIdentity.js";
import type { Product } from "./product.js";

export interface Entitlement {
  product: Product;
  feature: ObjectIdentity;
  name?: string;
  enabled: boolean;
  /**
   * When the subscription providing it ends. Absent for a metered subscription, which
   * has no end date.
   * @nullable
   */
  expires_at?: string | null;
}
