/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import type { AccountIdQueryParameter } from "./accountIdQueryParameter.js";
import type { PageParameter } from "./pageParameter.js";
import type { PageSizeParameter } from "./pageSizeParameter.js";

export type ListRefundsParams = {
  /**
   * 1-based page number; the first page when omitted.
   * @minimum 1
   * @maximum 2147483647
   */
  page?: PageParameter;
  /**
   * How many per page, 100 at most.
   * @minimum 1
   * @maximum 100
   */
  page_size?: PageSizeParameter;
  /**
   * Restrict to one of your accounts. All of them when omitted.
   */
  billing_account_id?: AccountIdQueryParameter;
  /**
   * Only the refunds of this invoice.
   */
  invoice_id?: string;
  /**
   * Only the refunds that belong to this order: those of its invoice, such as the refund of a
   * purchase that could not be delivered, and those it caused on an earlier invoice, such as
   * the difference returned after a downgrade.
   */
  order_id?: string;
};
