/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import type { PageParameter } from "./pageParameter.js";
import type { PageSizeParameter } from "./pageSizeParameter.js";

export type ListInvoiceItemsParams = {
  /**
   * 1-based page number; the first page when omitted.
   * @minimum 1
   * @maximum 2147483647
   */
  page?: PageParameter;
  /**
   * How many per page, 100 at most.
   * @minimum 1
   * @maximum 100
   */
  page_size?: PageSizeParameter;
};
