/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import type { Money } from "./money.js";

export interface MeteredUsage {
  billing_account_id: number;
  currency: string;
  /** Resources still metered in the projects the account currently pays for. */
  active_resource_count: number;
  /** Subscriptions billed by usage that the account currently pays for and that have not ended. */
  postpaid_subscription_count: number;
  /** The start of the seven days the amounts cover. */
  window_start: string;
  /** The end of those seven days, the time usage was last priced. */
  window_end: string;
  /** Usage priced in the window, before tax and before credit grants. Usage not yet priced is not included. */
  amount: Money;
  /**
   * `amount` per day. Over the window, or over the part of it since the account's usage began
   * when that is shorter, counting at least one day.
   */
  average_daily_amount: Money;
}
