/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */

/**
 * A decimal string, in the currency stated alongside it.
 *
 * **The currency is not part of this type.** It is carried by a `currency` field next to the
 * amount, or by the account the amount belongs to. Reading an amount without that field is
 * reading a number with no unit.
 *
 * It is a string rather than a JSON number because a JSON number is a float in most parsers,
 * and a float loses precision on the first arithmetic. Nothing on this platform puts an amount
 * through a float.
 */
export type Money = string;
