/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */

/**
 * `adopt` brings a resource that already existed under billing. It charges nothing at
 * the time and starts billing from the moment agreed.
 */
export type OrderType = (typeof OrderType)[keyof typeof OrderType];

export const OrderType = {
  purchase: "purchase",
  renew: "renew",
  change: "change",
  adopt: "adopt",
} as const;
