/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */

/**
 * When a plan change takes effect. `none` on anything that is not a change.
 *
 * `period_end` orders stay pending until the first period at the new price is paid. That period
 * is invoiced shortly before the current paid period ends and starts when it ends; if the
 * invoice is still unpaid by then, the order is canceled and the subscription renews or ends as
 * usual. Renewing in the meantime moves all of this along with it.
 */
export type OrderChangeEffective = (typeof OrderChangeEffective)[keyof typeof OrderChangeEffective];

export const OrderChangeEffective = {
  none: "none",
  immediate: "immediate",
  period_end: "period_end",
} as const;
