/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */

export interface PaymentMethodSetup {
  /**
   * The selected gateway supporting saved payment methods.
   * @minLength 1
   * @maxLength 32
   */
  payment_gateway: string;
  billing_account_id: number;
}
