/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentActionType } from "./paymentActionType.js";

/**
 * The customer's next interaction. The gateway reports the actual payment outcome separately.
 */
export interface PaymentAction {
  type: PaymentActionType;
  /** Identifies the browser adapter for an SDK action, for example stripe. */
  provider?: string;
  url?: string;
  /** QR content to render and scan, not an image URL. */
  qr_code?: string;
  /** Short-lived client credential for this payment's browser confirmation. */
  client_secret?: string;
  public_key?: string;
}
