/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */

export type PreviewInvoicePaymentParams = {
  /**
   * As in paying. True when omitted.
   */
  use_balance?: boolean;
  /**
   * As in paying. True when omitted.
   */
  use_credits?: boolean;
};
