/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import type { Money } from "./money.js";
import type { ObjectIdentity } from "./objectIdentity.js";
import type { PriceOptionBillingScheme } from "./priceOptionBillingScheme.js";
import type { PriceOptionInterval } from "./priceOptionInterval.js";
import type { PriceOptionType } from "./priceOptionType.js";
import type { Product } from "./product.js";

/**
 * A price's display terms, including archived prices referenced by an applicability list.
 */
export interface PriceOption {
  product: Product;
  plan: ObjectIdentity;
  billing_scheme: PriceOptionBillingScheme;
  unit_quantity: string;
  id: string;
  currency: string;
  type: PriceOptionType;
  interval: PriceOptionInterval;
  /** How many periods one purchase covers. */
  interval_count?: number;
  unit_amount?: Money;
  /** False once the price is archived. It still applies to purchases already made at this price. */
  active: boolean;
}
