/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import type { QuoteRenewalInterval } from "./quoteRenewalInterval.js";
import type { TerminationPolicy } from "./terminationPolicy.js";

/**
 * Price renewing a prepaid subscription. Give `price_id`, or `interval` with
 * `interval_count`, to renew for another term at the price currently sold for it. Naming
 * the current term, or giving neither, renews at the agreed amount. A term sold at several
 * prices that differ in termination policy is refused with 409
 * `BILLING_RENEWAL_OPTION_AMBIGUOUS` unless `termination_policy` or `price_id` is given.
 */
export interface QuoteRenewal {
  subscription_id: string;
  price_id?: string;
  interval?: QuoteRenewalInterval;
  /** @minimum 1 */
  interval_count?: number;
  /** With `interval` and `interval_count`, chooses among prices of that term that differ in termination policy. */
  termination_policy?: TerminationPolicy;
  /**
   * How many consecutive periods to renew for.
   * @minimum 1
   * @maximum 100
   */
  periods?: number;
}
