/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import type { CancellationRefundPreview } from "./cancellationRefundPreview.js";
import type { Money } from "./money.js";
import type { QuotedDiscount } from "./quotedDiscount.js";
import type { QuotedLine } from "./quotedLine.js";
import type { QuoteRenewalResult } from "./quoteRenewalResult.js";

/**
 * A computed price preview, without a saved quote or a price guarantee. No funds or discount
 * redemptions are reserved. Amounts use currency and exclude payment from credit grants or balance.
 */
export interface Quote {
  /**
   * Sum before discounts, less tax already included in the discounted line amounts, as on an
   * invoice. Null when any line cannot be priced. Zero for a cancellation-only quote.
   */
  subtotal: Money | null;
  /** Total line discounts. Null when any line cannot be priced; zero for a cancellation-only quote. */
  discount_amount: Money | null;
  /** Total tax on the discounted amounts. Null when any line cannot be priced; zero for a cancellation-only quote. */
  tax_amount: Money | null;
  /**
   * The one new discount evaluated for a purchase or order, without applying it. Null when
   * none is selected, pricing is incomplete, or the quote targets a renewal list or cancellation.
   * A confirmed order instead reports its recorded discount.
   */
  discount: QuotedDiscount | null;
  lines?: QuotedLine[];
  renewals?: QuoteRenewalResult[];
  /** What the cancellation requested would return. Present only when one was requested. */
  cancellation?: CancellationRefundPreview;
  /**
   * subtotal minus discount_amount plus tax_amount, before applying credit grants or balance.
   * For a purchase or order with no usage estimates, pass this as expected_amount at checkout.
   * A renewal list sums separate orders; use each renewal's total when confirming that order.
   * Refunds are not netted off: a cancellation-only quote has zero totals and its refund is in
   * cancellation. Usage estimates are projections, not checkout amounts.
   *
   * Null when any line could not be priced. What would be owed is not knowable then, and a
   * total that silently left the unpriced lines out would read as a smaller bill rather than
   * an incomplete one — the per-line `priced` flag is easy to skip, a missing total is not.
   */
  total: Money | null;
  currency: string;
}
