/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Why the refund was made. Clients map the code to their own wording. More codes may be added;
 * treat an unknown code as a refund without a stated reason.
 *
 * - `provisioning_failed`: the purchase could not be delivered.
 * - `order_expired`: the order expired after part of it had been paid.
 * - `order_canceled`: the account holder canceled the order after part of it had been paid.
 * - `change_canceled`: a scheduled change was withdrawn after part of it had been paid.
 * - `change_expired`: a scheduled change could not take effect before its time passed.
 * - `subscription_canceled`: the subscription was canceled and its unused value returned under
 *   its refund terms.
 * - `future_period_canceled`: a renewal that had not started yet was withdrawn.
 * - `downgrade_difference`: after a downgrade, the remaining value of what was paid, valued as refund
 *   policy `prorated` describes, minus the new configuration's cost for the remaining time at the
 *   change item's `refund_monthly_amount` and `refund_hourly_amount`. Nothing is refunded when that is
 *   zero or less.
 * - `usage_true_up`: usage priced again over the whole month cost less than was charged.
 * - `payment_not_applied`: a payment arrived after its invoice could no longer be paid.
 * - `operator`: made by the platform operator.
 */
export type RefundReason = (typeof RefundReason)[keyof typeof RefundReason];

export const RefundReason = {
  provisioning_failed: "provisioning_failed",
  order_expired: "order_expired",
  order_canceled: "order_canceled",
  change_canceled: "change_canceled",
  change_expired: "change_expired",
  subscription_canceled: "subscription_canceled",
  future_period_canceled: "future_period_canceled",
  downgrade_difference: "downgrade_difference",
  usage_true_up: "usage_true_up",
  payment_not_applied: "payment_not_applied",
  operator: "operator",
} as const;
