/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import type { Money } from "./money.js";
import type { ObjectIdentity } from "./objectIdentity.js";
import type { PaymentCancellationReason } from "./paymentCancellationReason.js";
import type { TransactionRefundDestination } from "./transactionRefundDestination.js";
import type { TransactionStatus } from "./transactionStatus.js";
import type { TransactionType } from "./transactionType.js";

/**
 * A funds operation. Each payment has one source; refunds identify the original successful transaction. Unknown gateway results remain pending. Payments from the balance or a gateway are distinct from credit-grant payments.
 */
export interface Transaction {
  invoice_id?: string;
  transaction_id?: string;
  /** The credit grant that paid, or for a refund, the credit grant restored. */
  credit_grant_id?: string;
  credit_grant?: ObjectIdentity;
  refund_id?: string;
  /**
   * Present on refunds. Where this part of the refund goes.
   *
   * - `balance`: back to the account balance.
   * - `credit`: back to the credit grant that paid, which keeps its original expiry.
   * - `gateway`: back to the payment method it was paid with.
   */
  refund_destination?: TransactionRefundDestination;
  /**
   * `failed` means the operation did not succeed; for a gateway payment, that the gateway declined
   * it. `canceled` means a gateway payment was withdrawn without collecting money. After either,
   * an invoice the payment was meant to pay remains open for another payment.
   */
  status?: TransactionStatus;
  /** Why the payment was withdrawn. Present with `canceled`. */
  cancellation_reason?: PaymentCancellationReason;
  payment_gateway?: string;
  method_type?: string;
  /**
   * Why it failed. Present with `failed`. For a declined gateway payment the value is the
   * gateway's own code, passed on unchanged: the card issuer's decline code when there is one
   * (Stripe's decline_code, such as insufficient_funds or lost_card), otherwise the gateway's
   * error code (Stripe's code, such as card_declined, expired_card or
   * payment_intent_authentication_failure). Clients map it to their own wording and treat an
   * unknown value as a generic decline.
   */
  failure_reason?: string;
  settled_at?: string;
  id: string;
  billing_account_id?: number;
  type: TransactionType;
  /**
   * Signed by type: positive for `topup` and `payment`, negative for `refund` and `payout`.
   * An `adjustment` is positive when it adds to the balance and negative when it takes from
   * it. For the other types the sign does not tell the effect on the balance: a payment from
   * the balance lowers it, while a payment by gateway or by credit leaves it unchanged.
   */
  amount: Money;
  /**
   * How much of this transaction is still available in the balance. Only top-ups, positive
   * adjustments and gateway payments later returned to the balance can be non-zero.
   */
  remaining_amount: Money;
  currency: string;
  reason?: string;
  created_at: string;
}
