/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Resource relationships
 * Resource claims, dependencies and reclamation policy. Types only.
 * OpenAPI spec version: v1
 */
import type { AttachmentState } from "./attachmentState.js";
import type { ResourceReference } from "./resourceReference.js";

export interface Attachment {
  id: string;
  usage_id: string;
  resource: ResourceReference;
  consumer: ResourceReference;
  state: AttachmentState;
  /** @minimum 1 */
  generation: number;
  device?: string;
  read_only: boolean;
  created_at: string;
  updated_at: string;
}
