/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Resource relationships
 * Resource claims, dependencies and reclamation policy. Types only.
 * OpenAPI spec version: v1
 */

/**
 * Automatic reclamation is disabled by default. When enabled, retention starts after the last live claim is confirmed released. Traffic, IO and consumer heartbeats do not affect eligibility.
 */
export interface IdlePolicy {
  enabled: boolean;
  /** @minimum 3600 */
  retention_seconds: number;
}
