/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Resource relationships
 * Resource claims, dependencies and reclamation policy. Types only.
 * OpenAPI spec version: v1
 */

/**
 * Pagination metadata for stable numbered pages. total_count is returned only when the operation can determine it without an unbounded scan.
 */
export interface OffsetPagination {
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  page_size: number;
  /** @minimum 0 */
  total_count?: number;
}
