/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Resource relationships
 * Resource claims, dependencies and reclamation policy. Types only.
 * OpenAPI spec version: v1
 */

export type ResourceUsageState = (typeof ResourceUsageState)[keyof typeof ResourceUsageState];

export const ResourceUsageState = {
  reserved: "reserved",
  active: "active",
  releasing: "releasing",
  released: "released",
} as const;
