/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Tunnel API
 * The user-facing API of Leaflow Tunnel: generating a tunnel for a project, reading its subscription address, and reading its traffic usage.
 *
 * ## Layer 4 only
 *
 * The platform offers tunnels at layers 2, 3 and 4. **Every endpoint in this document belongs to layer 4** and is served under `/tunnel/l4`. Layers 2 and 3 are not yet open and will carry their own prefixes.
 *
 * ## Layer 4 is entitled per project, and no project holds it by default
 *
 * **Every endpoint in this document requires the current project to have been entitled.** Without the entitlement each one answers 403 `TUNNEL_NOT_ENTITLED`. Entitlement is granted by the platform per project and cannot be obtained by the user.
 *
 * `TUNNEL_NOT_ENTITLED` and `TUNNEL_NOT_FOUND` state different things and cannot be handled as one. The first means the project has not been entitled; the second means it has, and no tunnel has been generated yet.
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * ## Conventions
 *
 * - **One layer 4 tunnel per project.** The path is therefore the singular `/tunnel/l4` and carries no id.
 *
 * - **Generation is idempotent.** Calling it again returns the existing tunnel rather than an error.
 *
 * - **The subscription address is a credential.** It is equivalent to a password, is returned only by `GET /tunnel/l4/subscription`, and appears neither in the tunnel itself nor in any list. Do not call that endpoint before the user asks for the address. Rotate it whenever it may have been exposed; every subscription already distributed stops working at once.
 *
 * - **`preparing` does not mean unusable.** The subscription link works while nodes are still being distributed, and its contents are derived at the moment it is fetched.
 *
 * - **Only `billed_bytes` decides whether the quota is exceeded.** A route may carry a multiplier such as 1.5× or 0×, so `raw_bytes`, the volume actually transferred, need not equal it. A `quota_bytes` of 0 means unlimited.
 *
 * - **Usage lags by up to one collection interval.** It suits usage control rather than settlement.
 *
 * - **Daily usage does not sum to the usage of the current period.** One is cut by calendar day and the other by billing period.
 * OpenAPI spec version: 1.0.0
 */
import type { Error } from "./models/error.js";

import type { ListL4TunnelUsageSeriesParams } from "./models/listL4TunnelUsageSeriesParams.js";

import type { SubscriptionResource } from "./models/subscriptionResource.js";

import type { TunnelResource } from "./models/tunnelResource.js";

import type { UsageResource } from "./models/usageResource.js";

import type { UsageSeriesResource } from "./models/usageSeriesResource.js";

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx =
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 407
  | 408
  | 409
  | 410
  | 411
  | 412
  | 413
  | 414
  | 415
  | 416
  | 417
  | 418
  | 419
  | 420
  | 421
  | 422
  | 423
  | 424
  | 426
  | 428
  | 429
  | 431
  | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes =
  | HTTPStatusCode1xx
  | HTTPStatusCode2xx
  | HTTPStatusCode3xx
  | HTTPStatusCode4xx
  | HTTPStatusCode5xx;

export type getL4TunnelResponse200 = {
  data: TunnelResource;
  status: 200;
};

export type getL4TunnelResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type getL4TunnelResponseSuccess = getL4TunnelResponse200 & {
  headers: Headers;
};
export type getL4TunnelResponseError = getL4TunnelResponseDefault & {
  headers: Headers;
};

export type getL4TunnelResponse = getL4TunnelResponseSuccess | getL4TunnelResponseError;

export const getGetL4TunnelUrl = () => {
  return `https://tunnel.leaflow.cloud/api/v1/tunnel/l4`;
};

/**
 * `TUNNEL_NOT_FOUND` means no tunnel has been generated yet.
 *
 * 403 `TUNNEL_NOT_ENTITLED` states something else: the project has not been entitled to layer 4 at all.
 *
 * The subscription address, the usage and the quota each have their own endpoint and are not repeated here.
 * @summary Get the layer 4 tunnel of the current project
 */
export const getL4Tunnel = async (
  options?: RequestInit,
  fetchFn?: typeof globalThis.fetch,
): Promise<getL4TunnelResponse> => {
  const res = await (fetchFn ?? fetch)(getGetL4TunnelUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getL4TunnelResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getL4TunnelResponse;
};

export type generateL4TunnelResponse200 = {
  data: TunnelResource;
  status: 200;
};

export type generateL4TunnelResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type generateL4TunnelResponseSuccess = generateL4TunnelResponse200 & {
  headers: Headers;
};
export type generateL4TunnelResponseError = generateL4TunnelResponseDefault & {
  headers: Headers;
};

export type generateL4TunnelResponse =
  | generateL4TunnelResponseSuccess
  | generateL4TunnelResponseError;

export const getGenerateL4TunnelUrl = () => {
  return `https://tunnel.leaflow.cloud/api/v1/tunnel/l4`;
};

/**
 * **Idempotent**: calling it again returns the existing tunnel rather than an error.
 *
 * Read the address from the subscription endpoint afterwards; it is not returned here.
 * @summary Generate the layer 4 tunnel
 */
export const generateL4Tunnel = async (
  options?: RequestInit,
  fetchFn?: typeof globalThis.fetch,
): Promise<generateL4TunnelResponse> => {
  const res = await (fetchFn ?? fetch)(getGenerateL4TunnelUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: generateL4TunnelResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as generateL4TunnelResponse;
};

export type getL4TunnelSubscriptionResponse200 = {
  data: SubscriptionResource;
  status: 200;
};

export type getL4TunnelSubscriptionResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type getL4TunnelSubscriptionResponseSuccess = getL4TunnelSubscriptionResponse200 & {
  headers: Headers;
};
export type getL4TunnelSubscriptionResponseError = getL4TunnelSubscriptionResponseDefault & {
  headers: Headers;
};

export type getL4TunnelSubscriptionResponse =
  | getL4TunnelSubscriptionResponseSuccess
  | getL4TunnelSubscriptionResponseError;

export const getGetL4TunnelSubscriptionUrl = () => {
  return `https://tunnel.leaflow.cloud/api/v1/tunnel/l4/subscription`;
};

/**
 * **This URL is a credential, equivalent to a password.** It yields every node of the project along with their passwords. It is returned here alone, and appears neither in the tunnel itself nor in any list.
 *
 * Do not call this endpoint before the user asks for the address.
 *
 * A `status` of `preparing` leaves the link usable; its contents are derived at the moment it is fetched.
 * @summary Get the subscription address
 */
export const getL4TunnelSubscription = async (
  options?: RequestInit,
  fetchFn?: typeof globalThis.fetch,
): Promise<getL4TunnelSubscriptionResponse> => {
  const res = await (fetchFn ?? fetch)(getGetL4TunnelSubscriptionUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getL4TunnelSubscriptionResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getL4TunnelSubscriptionResponse;
};

export type rotateL4TunnelSubscriptionResponse200 = {
  data: TunnelResource;
  status: 200;
};

export type rotateL4TunnelSubscriptionResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type rotateL4TunnelSubscriptionResponseSuccess = rotateL4TunnelSubscriptionResponse200 & {
  headers: Headers;
};
export type rotateL4TunnelSubscriptionResponseError = rotateL4TunnelSubscriptionResponseDefault & {
  headers: Headers;
};

export type rotateL4TunnelSubscriptionResponse =
  | rotateL4TunnelSubscriptionResponseSuccess
  | rotateL4TunnelSubscriptionResponseError;

export const getRotateL4TunnelSubscriptionUrl = () => {
  return `https://tunnel.leaflow.cloud/api/v1/tunnel/l4/subscription/rotate`;
};

/**
 * **This is the remedy for an exposed credential, and every subscription already distributed stops working at once.**
 *
 * The subscription token and the node passwords are replaced together, so every client has to fetch the subscription again before it can carry on. Confirm that this is the intended outcome before calling.
 *
 * A tunnel disabled by the platform cannot be rotated (`TUNNEL_DISABLED_FOR_ROTATE`); resolve the cause first.
 *
 * Read the new address from the subscription endpoint afterwards; **it is not returned here**.
 * @summary Rotate the subscription address and the node passwords
 */
export const rotateL4TunnelSubscription = async (
  options?: RequestInit,
  fetchFn?: typeof globalThis.fetch,
): Promise<rotateL4TunnelSubscriptionResponse> => {
  const res = await (fetchFn ?? fetch)(getRotateL4TunnelSubscriptionUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rotateL4TunnelSubscriptionResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as rotateL4TunnelSubscriptionResponse;
};

export type getL4TunnelUsageResponse200 = {
  data: UsageResource;
  status: 200;
};

export type getL4TunnelUsageResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type getL4TunnelUsageResponseSuccess = getL4TunnelUsageResponse200 & {
  headers: Headers;
};
export type getL4TunnelUsageResponseError = getL4TunnelUsageResponseDefault & {
  headers: Headers;
};

export type getL4TunnelUsageResponse =
  | getL4TunnelUsageResponseSuccess
  | getL4TunnelUsageResponseError;

export const getGetL4TunnelUsageUrl = () => {
  return `https://tunnel.leaflow.cloud/api/v1/tunnel/l4/usage`;
};

/**
 * Read live.
 *
 * Only `billed_bytes` decides whether the quota is exceeded: a route may carry a multiplier such as 1.5× or 0×, so `raw_bytes`, the volume actually transferred, need not equal it. A `quota_bytes` of 0 means unlimited.
 * @summary Get the usage of the current period
 */
export const getL4TunnelUsage = async (
  options?: RequestInit,
  fetchFn?: typeof globalThis.fetch,
): Promise<getL4TunnelUsageResponse> => {
  const res = await (fetchFn ?? fetch)(getGetL4TunnelUsageUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getL4TunnelUsageResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getL4TunnelUsageResponse;
};

export type listL4TunnelUsageSeriesResponse200 = {
  data: UsageSeriesResource;
  status: 200;
};

export type listL4TunnelUsageSeriesResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type listL4TunnelUsageSeriesResponseSuccess = listL4TunnelUsageSeriesResponse200 & {
  headers: Headers;
};
export type listL4TunnelUsageSeriesResponseError = listL4TunnelUsageSeriesResponseDefault & {
  headers: Headers;
};

export type listL4TunnelUsageSeriesResponse =
  | listL4TunnelUsageSeriesResponseSuccess
  | listL4TunnelUsageSeriesResponseError;

export const getListL4TunnelUsageSeriesUrl = (params?: ListL4TunnelUsageSeriesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://tunnel.leaflow.cloud/api/v1/tunnel/l4/usage/series?${stringifiedParams}`
    : `https://tunnel.leaflow.cloud/api/v1/tunnel/l4/usage/series`;
};

/**
 * Cut by calendar day. A day carrying no traffic is absent rather than zero, so a chart has to fill the date axis itself.
 *
 * These days do not sum to the usage of the current period, which is cut by billing period. Resetting the usage of the current period leaves every daily total in place.
 * @summary Get daily usage
 */
export const listL4TunnelUsageSeries = async (
  params?: ListL4TunnelUsageSeriesParams,
  options?: RequestInit,
  fetchFn?: typeof globalThis.fetch,
): Promise<listL4TunnelUsageSeriesResponse> => {
  const res = await (fetchFn ?? fetch)(getListL4TunnelUsageSeriesUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listL4TunnelUsageSeriesResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as listL4TunnelUsageSeriesResponse;
};
