/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import type { AllowanceSourceType } from "./allowanceSourceType.js";
import type { AllowanceStatus } from "./allowanceStatus.js";
import type { ObjectIdentity } from "./objectIdentity.js";
import type { Product } from "./product.js";

export interface Allowance {
  /** Optional issuance key, unique within this billing account. */
  idempotency_key?: string;
  subscription_id?: string;
  id: string;
  billing_account_id?: number;
  product: Product;
  meter: ObjectIdentity;
  /** The unit it is counted in, such as `MiB`. */
  unit?: string;
  /**
   * `included` came with a recurring purchase and ends with its subscription, `promotional` was
   * granted.
   */
  source_type: AllowanceSourceType;
  name: string;
  /** How much was granted. */
  quantity: string;
  /** How much is left. */
  remaining_quantity: string;
  /**
   * Lower values are consumed first. At equal priority, earlier expiry and then earlier issuance take
   * precedence.
   */
  priority?: number;
  status: AllowanceStatus;
  valid_from: string;
  /**
   * When it lapses. Anything unused at that point is lost; it is not refunded and does
   * not carry over. Absent when it does not expire on its own.
   * @nullable
   */
  valid_until?: string | null;
}
