/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */

export type AllowanceStatus = (typeof AllowanceStatus)[keyof typeof AllowanceStatus];

export const AllowanceStatus = {
  active: "active",
  depleted: "depleted",
  expired: "expired",
  voided: "voided",
} as const;
