/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Who asked for it. `project_deletion` means the project was deleted.
 */
export type CancellationOrigin = (typeof CancellationOrigin)[keyof typeof CancellationOrigin];

export const CancellationOrigin = {
  customer: "customer",
  operator: "operator",
  project_deletion: "project_deletion",
} as const;
