/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */

/**
 * What a given `code` carries alongside the message. The keys depend on the code,
 * and a client that does not recognise one ignores it.
 */
export type ErrorMeta = { [key: string]: unknown };
