/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */

export type ListProjectSpendGroupBy =
  (typeof ListProjectSpendGroupBy)[keyof typeof ListProjectSpendGroupBy];

export const ListProjectSpendGroupBy = {
  product: "product",
  plan: "plan",
  resource: "resource",
} as const;
