/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import type { FromParameter } from "./fromParameter.js";
import type { OrderStatus } from "./orderStatus.js";
import type { PageParameter } from "./pageParameter.js";
import type { PageSizeParameter } from "./pageSizeParameter.js";
import type { ToParameter } from "./toParameter.js";

export type ListProjectOrdersParams = {
  /**
   * 1-based page number; the first page when omitted.
   * @minimum 1
   * @maximum 2147483647
   */
  page?: PageParameter;
  /**
   * How many per page, 100 at most.
   * @minimum 1
   * @maximum 100
   */
  page_size?: PageSizeParameter;
  status?: OrderStatus;
  from?: FromParameter;
  /**
   * Exclusive.
   */
  to?: ToParameter;
};
