/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import type { PageParameter } from "./pageParameter.js";
import type { PageSizeParameter } from "./pageSizeParameter.js";
import type { ProductID } from "./productID.js";

export type ListProjectEntitlementsParams = {
  /**
   * 1-based page number; the first page when omitted.
   * @minimum 1
   * @maximum 2147483647
   */
  page?: PageParameter;
  /**
   * How many per page, 100 at most.
   * @minimum 1
   * @maximum 100
   */
  page_size?: PageSizeParameter;
  /**
   * Filter by ID or lookup key. A lookup key is scoped to the product.
   */
  product_id?: ProductID;
};
