/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */

/**
 * A catalog object inlined for display.
 */
export interface ObjectIdentity {
  lookup_key?: string;
  id: string;
  name: string;
}
