/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import type { Money } from "./money.js";
import type { OrderItemBillingType } from "./orderItemBillingType.js";
import type { OrderItemConfiguration } from "./orderItemConfiguration.js";
import type { OrderItemInterval } from "./orderItemInterval.js";
import type { OrderItemStatus } from "./orderItemStatus.js";
import type { Product } from "./product.js";
import type { ProductID } from "./productID.js";
import type { RefundPolicy } from "./refundPolicy.js";
import type { TerminationPolicy } from "./terminationPolicy.js";

/**
 * Frozen purchase terms. Monetary fields come from related invoice-line snapshots and are absent
 * when there is no immediate invoice. Later catalog changes do not reprice this line. A new service
 * purchase creates its pending subscription when this item is recorded, not when payment succeeds.
 */
export interface OrderItem {
  /** @minimum 0 */
  position?: number;
  configuration?: OrderItemConfiguration;
  /**
   * Stable Billing subscription ID. A new prepaid or postpaid service purchase returns the
   * pending subscription here; renewals and changes reference the existing subscription, which
   * keeps its ID. Absent for delivery without a subscription. This is not a business resource ID.
   */
  subscription_id?: string;
  interval: OrderItemInterval;
  /** @minimum 1 */
  interval_count?: number;
  termination_policy?: TerminationPolicy;
  refund_policy?: RefundPolicy;
  /**
   * Prepaid items only: the plan's one-month prepaid price for this item's quantity before tax, frozen
   * at purchase, used to value time used under a prorated refund or a downgrade. Null when the plan has
   * no prepaid period shorter than the one bought.
   * @nullable
   */
  refund_monthly_amount?: string | null;
  /**
   * Prepaid items only: the plan's postpaid hourly price for this item's quantity before tax, frozen at
   * purchase, used for time used short of a full month. Null when the plan has no postpaid price.
   * @nullable
   */
  refund_hourly_amount?: string | null;
  completes_on_payment: boolean;
  recurring_amount?: string;
  setup_amount?: string;
  /** The payment timing of the selected price. */
  billing_type: OrderItemBillingType;
  /** Total tax after discounts, including any tax already included in the price. */
  tax_amount?: string;
  /** The part of tax_amount already included in gross_amount; it is not charged again. */
  tax_included_amount?: string;
  id: string;
  order_id?: string;
  price_id: string;
  /** Which service this line belongs to. */
  product_id?: ProductID;
  product?: Product;
  /** Which plan was bought. */
  plan_id: string;
  /**
   * What it was called when bought. It does not follow later catalogue renames and is
   * not translated.
   */
  plan_name: string;
  quantity: string;
  /**
   * The unit amount of the price this line is charged under. Absent for a tiered price, which has no
   * single unit amount, and for a change that takes effect at once, which is charged as `gross_amount`
   * describes.
   */
  unit_amount?: Money;
  /**
   * Before discounts: the price applied to the quantity, which for a per-unit price is `unit_amount`
   * times `quantity`; a minimum charge can make it higher. For an upgrade that takes effect at once it is
   * the new price minus the old price for the time left in the paid period, both at the subscription's
   * own period price, and the period end does not move; a downgrade charges nothing and may refund the
   * difference instead. A change between equal period prices charges and refunds nothing. The setup fee is not part of it; see `setup_amount`.
   *
   * Under an inclusive tax rate it includes tax, as the price does, and the included part is
   * `tax_included_amount`. A renewal at the agreed terms is the exception: the agreed amount excludes
   * tax, and tax is added to it.
   */
  gross_amount?: Money;
  /**
   * The reduction on this line: from the coupon the order uses and, for a renewal at the agreed terms,
   * from the discount the subscription carries.
   *
   * A carried discount is part of the agreed amount. It is listed here, and `gross_amount` is then
   * `unit_amount` times `quantity`, except in two cases where `gross_amount` is the agreed amount and
   * the carried discount is already reflected in it: the renewal order also uses a coupon the account
   * holds, or the account's tax rate is inclusive.
   */
  discount_amount?: Money;
  /** `gross_amount` less `discount_amount`. */
  amount?: Money;
  currency: string;
  /** @nullable */
  period_start?: string | null;
  /** @nullable */
  period_end?: string | null;
  status: OrderItemStatus;
}
