/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import type { OffsetPagination } from "./offsetPagination.js";
import type { Order } from "./order.js";

export interface OrderList {
  items: Order[];
  pagination: OffsetPagination;
}
