/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import type { TerminationPolicy } from "./terminationPolicy.js";

/**
 * A cancellation to quote: what ending these subscriptions together would return. One mode per
 * request; to compare, quote `immediate` and `period_end` separately.
 */
export interface QuoteCancellation {
  /**
   * The subscriptions to end together, all of one service. Every subscription released with a resource must be included.
   * @minItems 1
   * @maxItems 50
   */
  subscription_ids: string[];
  mode: TerminationPolicy;
}
