/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import type { QuoteCancellation } from "./quoteCancellation.js";
import type { QuoteLine } from "./quoteLine.js";
import type { QuoteRenewal } from "./quoteRenewal.js";

/**
 * Quote exactly one target: purchase `lines`, an existing `order_id`, `renewals` or a `cancellation`. Giving none or
 * more than one, or a `promotion_code` with `renewals` or a `cancellation`, fails with HTTP 400
 * `BILLING_PURCHASE_INVALID` and `meta.field` naming the offending field. Without a code, an
 * applicable account discount is selected. An explicit code is evaluated without reserving or
 * consuming a redemption and must be supplied again when confirming checkout through Billing.
 */
export interface QuoteRequest {
  /**
   * A proposed purchase, priced with the project's current billing account. Future usage
   * estimates cannot be combined with a promotion code or used as a checkout amount.
   * @minItems 1
   * @maxItems 100
   */
  lines?: QuoteLine[];
  /**
   * Preview checkout of this existing order. Its recorded purchase terms supply every line, and a
   * confirmed order returns its recorded amounts. A preview does not change the order.
   */
  order_id?: string;
  /**
   * Preview renewing these subscriptions, each at most once. Each entry represents a separate
   * renewal order. To preview a new promotion code, create a renewal order and quote it by order_id.
   * @minItems 1
   * @maxItems 100
   */
  renewals?: QuoteRenewal[];
  cancellation?: QuoteCancellation;
  /**
   * @minLength 1
   * @maxLength 64
   */
  promotion_code?: string;
}
