/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import type { Money } from "./money.js";
import type { QuoteRenewalResultInterval } from "./quoteRenewalResultInterval.js";

/**
 * What renewing would charge. Renewing the same subscription for the same term and number
 * of periods charges exactly `total`, unless prices or the discounts the account holds
 * change in between.
 */
export interface QuoteRenewalResult {
  /** Which renewal of the request this answers. */
  index: number;
  subscription_id: string;
  /** The price the renewal is charged under. */
  price_id: string;
  interval: QuoteRenewalResultInterval;
  interval_count: number;
  periods: number;
  /**
   * The price of the periods before the discounts the account holds. A discount the
   * subscription already carries is reflected here. Contains tax only where the price
   * itself includes it.
   */
  amount: Money;
  /** The reduction from a discount the account holds. */
  discount_amount: Money;
  /** Tax on the discounted amount. */
  tax_amount: Money;
  /** The part of `tax_amount` already contained in `amount`. */
  tax_included_amount: Money;
  /**
   * What renewing would charge: `amount` less `discount_amount`, plus `tax_amount`, less
   * `tax_included_amount`.
   */
  total: Money;
}
