/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import type { Money } from "./money.js";
import type { Product } from "./product.js";

export interface SpendRow {
  product?: Product;
  plan_id?: string;
  plan_name?: string;
  /** Present only when grouped by resource. */
  resource_id?: string;
  amount: Money;
  currency: string;
}
