/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Monitoring API
 * Monitoring for your own project: enroll machines, read metrics, work through incidents, schedule maintenance windows, and set availability targets.
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * ## Two distinctions worth keeping straight
 *
 * - **Disabling is not deleting.** `POST /servers/{id}/disable` is reversible and preserves all history. `DELETE /servers/{id}` also removes the monitored host, its history and every incident recorded against it, and cannot be undone.
 * - **Recovery is not closure.** `incident_status` reports whether monitoring considers the problem recovered; `closed_at` reports whether someone has finished handling it. An incident that has not recovered may still be closed as an accepted risk.
 *
 * ## The PSK is returned once
 *
 * Enrollment and rotation responses include `tls_psk`. No other endpoint will return it again, so store it immediately. If it is lost, rotate once more — at the cost of updating the agent configuration on the monitored machine.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const assignIncidentRequestBodyAssigneeDisplayNameMax = 255;

export const assignIncidentRequestBodyAssigneeUserIdMax = 255;

export const AssignIncidentRequestBody = zod.strictObject({
  assignee_display_name: zod
    .string()
    .max(assignIncidentRequestBodyAssigneeDisplayNameMax)
    .optional()
    .describe(
      "Defaults to the user id. The timeline keeps a copy of the name as it was at the time",
    ),
  assignee_user_id: zod.string().max(assignIncidentRequestBodyAssigneeUserIdMax).optional(),
});

export type AssignIncidentRequestBody = zod.input<typeof AssignIncidentRequestBody>;
export type AssignIncidentRequestBodyOutput = zod.output<typeof AssignIncidentRequestBody>;
