/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Monitoring API
 * Monitoring for your own project: enroll machines, read metrics, work through incidents, schedule maintenance windows, and set availability targets.
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * ## Two distinctions worth keeping straight
 *
 * - **Disabling is not deleting.** `POST /servers/{id}/disable` is reversible and preserves all history. `DELETE /servers/{id}` also removes the monitored host, its history and every incident recorded against it, and cannot be undone.
 * - **Recovery is not closure.** `incident_status` reports whether monitoring considers the problem recovered; `closed_at` reports whether someone has finished handling it. An incident that has not recovered may still be closed as an accepted risk.
 *
 * ## The PSK is returned once
 *
 * Enrollment and rotation responses include `tls_psk`. No other endpoint will return it again, so store it immediately. If it is lost, rotate once more — at the cost of updating the agent configuration on the monitored machine.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { TemplateBindingRequest } from "./templateBindingRequest.zod.js";

export const enableMonitoringRequestBodyAddressMax = 255;

export const enableMonitoringRequestBodyAgentPortMin = 0;
export const enableMonitoringRequestBodyAgentPortMax = 65535;

export const enableMonitoringRequestBodyDescriptionMax = 2000;

export const enableMonitoringRequestBodyNameMax = 128;

export const EnableMonitoringRequestBody = zod.strictObject({
  address: zod.string().min(1).max(enableMonitoringRequestBodyAddressMax),
  address_kind: zod.enum(["ip", "dns"]),
  agent_mode: zod
    .enum(["PASSIVE", "ACTIVE"])
    .optional()
    .describe("Empty selects passive mode, which requires the least agent-side configuration"),
  agent_port: zod
    .int()
    .min(enableMonitoringRequestBodyAgentPortMin)
    .max(enableMonitoringRequestBodyAgentPortMax)
    .optional()
    .describe("0 uses the default of 10050"),
  description: zod.string().max(enableMonitoringRequestBodyDescriptionMax).optional(),
  name: zod.string().min(1).max(enableMonitoringRequestBodyNameMax),
  template_bindings: zod.array(TemplateBindingRequest).nullish(),
});

export type EnableMonitoringRequestBody = zod.input<typeof EnableMonitoringRequestBody>;
export type EnableMonitoringRequestBodyOutput = zod.output<typeof EnableMonitoringRequestBody>;
