/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Monitoring API
 * Monitoring for your own project: enroll machines, read metrics, work through incidents, schedule maintenance windows, and set availability targets.
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * ## Two distinctions worth keeping straight
 *
 * - **Disabling is not deleting.** `POST /servers/{id}/disable` is reversible and preserves all history. `DELETE /servers/{id}` also removes the monitored host, its history and every incident recorded against it, and cannot be undone.
 * - **Recovery is not closure.** `incident_status` reports whether monitoring considers the problem recovered; `closed_at` reports whether someone has finished handling it. An incident that has not recovered may still be closed as an accepted risk.
 *
 * ## The PSK is returned once
 *
 * Enrollment and rotation responses include `tls_psk`. No other endpoint will return it again, so store it immediately. If it is lost, rotate once more — at the cost of updating the agent configuration on the monitored machine.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const listIncidentsParamsLimitDefault = 50;
export const listIncidentsParamsLimitMax = 200;

export const listIncidentsParamsOffsetMin = 0;
export const listIncidentsParamsOffsetMax = 10000;

export const listIncidentsParamsKeywordMax = 255;

export const ListIncidentsParams = zod.strictObject({
  limit: zod
    .int()
    .min(1)
    .max(listIncidentsParamsLimitMax)
    .default(listIncidentsParamsLimitDefault)
    .describe("Maximum number of records in this page"),
  offset: zod
    .int()
    .min(listIncidentsParamsOffsetMin)
    .max(listIncidentsParamsOffsetMax)
    .optional()
    .describe(
      "Number of records to skip. For deeper paging, use the cursor-paged endpoint instead",
    ),
  server_id: zod.string().optional().describe("Restrict to a single machine"),
  web_check_id: zod
    .string()
    .optional()
    .describe("Restrict to a single web check. Combines with server_id rather than replacing it"),
  incident_status: zod.enum(["PROBLEM", "RESOLVED"]).optional(),
  min_severity: zod
    .enum(["NOT_CLASSIFIED", "INFORMATION", "WARNING", "AVERAGE", "HIGH", "DISASTER"])
    .optional()
    .describe("Matches at or above this severity, not exactly this severity"),
  started_after: zod.iso.datetime({ offset: true }).optional(),
  started_before: zod.iso.datetime({ offset: true }).optional(),
  active_from: zod.iso
    .datetime({ offset: true })
    .optional()
    .describe(
      "Incidents that **overlap** [active_from, active_to]. This is what you want when overlaying incident bands on a metric chart",
    ),
  active_to: zod.iso.datetime({ offset: true }).optional(),
  tag: zod
    .array(zod.string())
    .nullish()
    .describe("Given as `key` or `key=value`, repeatable. Multiple tags are combined with AND"),
  assignee_user_id: zod.string().optional(),
  closed: zod
    .enum(["true", "false"])
    .optional()
    .describe("Whether someone has finished handling it here. Independent of `incident_status`"),
  acknowledged: zod.enum(["true", "false"]).optional(),
  unassigned: zod.enum(["true", "false"]).optional(),
  keyword: zod.string().max(listIncidentsParamsKeywordMax).optional(),
});

export type ListIncidentsParams = zod.input<typeof ListIncidentsParams>;
export type ListIncidentsParamsOutput = zod.output<typeof ListIncidentsParams>;
