/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Monitoring API
 * Monitoring for your own project: enroll machines, read metrics, work through incidents, schedule maintenance windows, and set availability targets.
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * ## Two distinctions worth keeping straight
 *
 * - **Disabling is not deleting.** `POST /servers/{id}/disable` is reversible and preserves all history. `DELETE /servers/{id}` also removes the monitored host, its history and every incident recorded against it, and cannot be undone.
 * - **Recovery is not closure.** `incident_status` reports whether monitoring considers the problem recovered; `closed_at` reports whether someone has finished handling it. An incident that has not recovered may still be closed as an accepted risk.
 *
 * ## The PSK is returned once
 *
 * Enrollment and rotation responses include `tls_psk`. No other endpoint will return it again, so store it immediately. If it is lost, rotate once more — at the cost of updating the agent configuration on the monitored machine.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const putStatusPageComponentRequestBodyAutoStatusMinSeverityDefault = `AVERAGE`;
export const putStatusPageComponentRequestBodyDescriptionMax = 2000;

export const putStatusPageComponentRequestBodyNameMax = 128;

export const putStatusPageComponentRequestBodyOnlyShowIfDegradedDefault = false;
export const putStatusPageComponentRequestBodyShowUptimeDefault = true;

export const PutStatusPageComponentRequestBody = zod.strictObject({
  auto_status_min_severity: zod
    .enum(["ANY", "INFORMATION", "WARNING", "AVERAGE", "HIGH", "DISASTER"])
    .default(putStatusPageComponentRequestBodyAutoStatusMinSeverityDefault)
    .describe("Alerts below this severity do not change the status of this row"),
  description: zod.string().max(putStatusPageComponentRequestBodyDescriptionMax).optional(),
  group_id: zod.uuid().optional().describe("Empty leaves the component ungrouped"),
  name: zod
    .string()
    .min(1)
    .max(putStatusPageComponentRequestBodyNameMax)
    .describe("Customer-facing copy; appears verbatim on the public page"),
  only_show_if_degraded: zod
    .boolean()
    .default(putStatusPageComponentRequestBodyOnlyShowIfDegradedDefault),
  show_uptime: zod.boolean().default(putStatusPageComponentRequestBodyShowUptimeDefault),
  started_on: zod.iso
    .datetime({ offset: true })
    .optional()
    .describe(
      "Meaningful only at creation and immutable afterwards. Empty selects the current moment",
    ),
});

export type PutStatusPageComponentRequestBody = zod.input<typeof PutStatusPageComponentRequestBody>;
export type PutStatusPageComponentRequestBodyOutput = zod.output<
  typeof PutStatusPageComponentRequestBody
>;
