/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Monitoring API
 * Monitoring for your own project: enroll machines, read metrics, work through incidents, schedule maintenance windows, and set availability targets.
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * ## Two distinctions worth keeping straight
 *
 * - **Disabling is not deleting.** `POST /servers/{id}/disable` is reversible and preserves all history. `DELETE /servers/{id}` also removes the monitored host, its history and every incident recorded against it, and cannot be undone.
 * - **Recovery is not closure.** `incident_status` reports whether monitoring considers the problem recovered; `closed_at` reports whether someone has finished handling it. An incident that has not recovered may still be closed as an accepted risk.
 *
 * ## The PSK is returned once
 *
 * Enrollment and rotation responses include `tls_psk`. No other endpoint will return it again, so store it immediately. If it is lost, rotate once more — at the cost of updating the agent configuration on the monitored machine.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const StatusPageDomainResource = zod.strictObject({
  certificate_not_after: zod.iso
    .datetime({ offset: true })
    .nullable()
    .describe("When the current certificate expires"),
  certificate_status: zod
    .enum(["NONE", "PENDING", "ACTIVE", "FAILED"])
    .describe("NONE means no certificate has been requested for this domain yet"),
  domain: zod.string().describe("The bound custom domain. Empty means none is bound"),
  expected_cname: zod.string().describe("The value the domain must point at"),
  last_error: zod
    .string()
    .describe("Why the most recent issuance attempt failed. Empty when it did not"),
  observed_cname: zod
    .string()
    .describe("What the domain currently resolves to. Empty when it resolves to nothing"),
  public_url: zod
    .string()
    .describe("The address this page is served at, taking the custom domain into account"),
  verified: zod.boolean().describe("Whether the domain currently points at the status page"),
  verified_at: zod.iso
    .datetime({ offset: true })
    .nullable()
    .describe("When ownership was last confirmed"),
});

export type StatusPageDomainResource = zod.input<typeof StatusPageDomainResource>;
export type StatusPageDomainResourceOutput = zod.output<typeof StatusPageDomainResource>;
