/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Canopy API
 * Management of API keys, together with the models available and the usage recorded against them.
 *
 * **These endpoints do not perform inference.** Requests are issued to the forwarding address, which accepts the OpenAI, Anthropic and Gemini request formats:
 *
 * ```
 * POST /v1/chat/completions                    OpenAI
 * POST /v1/messages                            Anthropic
 * POST /v1beta/models/{model}:generateContent  Gemini
 * ```
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * These endpoints do not accept an API key, and the forwarding endpoints do not accept a scoped token.
 *
 * ## Conventions
 *
 * - **The plaintext of an API key is returned once.** The `secret` appears in the response that issues it and is returned by no other endpoint. A key that has been lost has to be revoked and reissued.
 * - **Disabling and revoking are distinct.** A disabled key may be enabled again at any time, while a revocation is irreversible and is intended for a key that has been exposed. Neither removes the record, and the usage the key accrued remains readable.
 * - **A usage query must carry a time range**, spanning no more than 31 days. `from` and `to` carry a timezone offset, which the server does not infer.
 * - **The request and response bodies do not appear in the ledger.** They are not recorded. Quote the `upstream_request_id` from the response when reporting a problem.
 * - **Usage may be estimated.** The upstream provider does not report usage on every request. Where it does not, `usage_source` is `estimated` and the figures are derived from the character classes of the payload, to within roughly fifteen per cent.
 * - **The service is enabled before use.** A project enables the model platform once, through `create-service`; the forwarding endpoints refuse its requests until the service is `active`. Requests are then billed under the service's subscription by the tokens they use, at the rates stated in each model's `pricing`.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { Money } from "./money.zod.js";

export const QuotedLine = zod
  .strictObject({
    priced: zod
      .boolean()
      .describe(
        "Whether the line can be priced. When false, unpriced_reason states what is missing.",
      ),
    unpriced_reason: zod
      .enum(["none", "no_price"])
      .describe("Why no price was found; `none` while `priced` is true."),
    plan_name: zod.string(),
    unit_amount: zod
      .union([Money, zod.null()])
      .describe("Unit price before discounts, with tax included only where the price includes it."),
    quantity: zod.string().describe("The quantity priced."),
    amount: zod
      .union([Money, zod.null()])
      .describe(
        "Before discounts, including any setup charges. Contains tax only where the price includes it.\nZero for a priced order item with no immediate charge.",
      ),
    discount_amount: zod
      .union([Money, zod.null()])
      .describe("Total reduction on this line, including any committed recurring discount."),
    tax_amount: zod
      .union([Money, zod.null()])
      .describe(
        "Tax on the discounted amount, including any tax already contained in that amount.",
      ),
    tax_included_amount: zod
      .union([Money, zod.null()])
      .describe("The part of tax_amount already contained in amount minus discount_amount."),
    total: zod
      .union([Money, zod.null()])
      .describe("amount minus discount_amount plus tax_amount minus tax_included_amount."),
    estimated_usage_amount: zod
      .union([Money, zod.null()])
      .describe(
        "Projected charge for this line's future usage over the period stated by the quoting operation,\nat current rates, before discounts and tax and not rounded. Not part of amount or total and\nnot collected at checkout. Null when the line is not billed for usage or its usage cannot be\npriced.",
      ),
    currency: zod.string(),
  })
  .describe(
    "One calculated purchase line. Fixed purchase amounts are rounded as checkout rounds them.\nWhen priced is false, every monetary field is null. A priced line without an\nimmediate charge has zero amounts; an unavailable unit price remains null.",
  );

export type QuotedLine = zod.input<typeof QuotedLine>;
export type QuotedLineOutput = zod.output<typeof QuotedLine>;
