/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Canopy API
 * Management of API keys, together with the models available and the usage recorded against them.
 *
 * **These endpoints do not perform inference.** Requests are issued to the forwarding address, which accepts the OpenAI, Anthropic and Gemini request formats:
 *
 * ```
 * POST /v1/chat/completions                    OpenAI
 * POST /v1/messages                            Anthropic
 * POST /v1beta/models/{model}:generateContent  Gemini
 * ```
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * These endpoints do not accept an API key, and the forwarding endpoints do not accept a scoped token.
 *
 * ## Conventions
 *
 * - **The plaintext of an API key is returned once.** The `secret` appears in the response that issues it and is returned by no other endpoint. A key that has been lost has to be revoked and reissued.
 * - **Disabling and revoking are distinct.** A disabled key may be enabled again at any time, while a revocation is irreversible and is intended for a key that has been exposed. Neither removes the record, and the usage the key accrued remains readable.
 * - **A usage query must carry a time range**, spanning no more than 31 days. `from` and `to` carry a timezone offset, which the server does not infer.
 * - **The request and response bodies do not appear in the ledger.** They are not recorded. Quote the `upstream_request_id` from the response when reporting a problem.
 * - **Usage may be estimated.** The upstream provider does not report usage on every request. Where it does not, `usage_source` is `estimated` and the figures are derived from the character classes of the payload, to within roughly fifteen per cent.
 * - **The service is enabled before use.** A project enables the model platform once, through `create-service`; the forwarding endpoints refuse its requests until the service is `active`. Requests are then billed under the service's subscription by the tokens they use, at the rates stated in each model's `pricing`.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const RequestResource = zod.strictObject({
  api_key_id: zod.uuid(),
  cache_read_tokens: zod
    .int()
    .describe(
      "The portion served from the upstream prefix cache, which costs an order of magnitude less than ordinary input",
    ),
  cache_write_tokens: zod.int(),
  error_code: zod.string().describe("The error code on failure. Empty on success"),
  finished_at: zod.iso.datetime({ offset: true }).nullable(),
  first_token_at: zod.iso.datetime({ offset: true }).nullable(),
  id: zod.uuid(),
  input_tokens: zod.int(),
  model_id: zod.string().describe("The model named in the request"),
  output_tokens: zod.int(),
  reasoning_tokens: zod.int(),
  retries: zod.int(),
  started_at: zod.iso.datetime({ offset: true }),
  status: zod.enum(["in_flight", "succeeded", "refused", "upstream_failed", "client_aborted"]),
  stream: zod.boolean(),
  upstream_request_id: zod
    .string()
    .describe("The id of the request on the upstream side. Quote it when reporting a problem"),
  upstream_status: zod
    .int()
    .describe("The HTTP status returned upstream. 0 indicates that the request never reached it"),
  usage_source: zod
    .enum(["none", "upstream", "estimated"])
    .describe(
      "upstream means the figures were reported by the provider; estimated means they were derived from the character classes of the payload",
    ),
});

export type RequestResource = zod.input<typeof RequestResource>;
export type RequestResourceOutput = zod.output<typeof RequestResource>;
