/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Canopy API
 * Management of API keys, together with the models available and the usage recorded against them.
 *
 * **These endpoints do not perform inference.** Requests are issued to the forwarding address, which accepts the OpenAI, Anthropic and Gemini request formats:
 *
 * ```
 * POST /v1/chat/completions                    OpenAI
 * POST /v1/messages                            Anthropic
 * POST /v1beta/models/{model}:generateContent  Gemini
 * ```
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * These endpoints do not accept an API key, and the forwarding endpoints do not accept a scoped token.
 *
 * ## Conventions
 *
 * - **The plaintext of an API key is returned once.** The `secret` appears in the response that issues it and is returned by no other endpoint. A key that has been lost has to be revoked and reissued.
 * - **Disabling and revoking are distinct.** A disabled key may be enabled again at any time, while a revocation is irreversible and is intended for a key that has been exposed. Neither removes the record, and the usage the key accrued remains readable.
 * - **A usage query must carry a time range**, spanning no more than 31 days. `from` and `to` carry a timezone offset, which the server does not infer.
 * - **The request and response bodies do not appear in the ledger.** They are not recorded. Quote the `upstream_request_id` from the response when reporting a problem.
 * - **Usage may be estimated.** The upstream provider does not report usage on every request. Where it does not, `usage_source` is `estimated` and the figures are derived from the character classes of the payload, to within roughly fifteen per cent.
 * - **The service is enabled before use.** A project enables the model platform once, through `create-service`; the forwarding endpoints refuse its requests until the service is `active`. Requests are then billed under the service's subscription by the tokens they use, at the rates stated in each model's `pricing`.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ServiceResource = zod
  .strictObject({
    status: zod
      .enum(["inactive", "pending", "active", "failed"])
      .describe(
        "`inactive` has never been enabled or its subscription has ended; `pending` awaits acceptance of its order; `active` accepts requests on the forwarding endpoints; `failed` means the enablement failed, as `failure_reason` states. An `inactive` or `failed` service can be enabled again.",
      ),
    failure_reason: zod
      .union([
        zod.literal("order_declined"),
        zod.literal("order_canceled"),
        zod.literal("order_expired"),
        zod.literal(null),
      ])
      .nullable()
      .describe(
        "Why the enablement failed; null unless `status` is `failed`. `order_declined` means Billing did not accept the order, for example because the billing account is suspended; `order_canceled` means the order was withdrawn; `order_expired` means its checkout was not confirmed in time.",
      ),
    order_id: zod
      .uuid()
      .nullable()
      .describe(
        "The order that enabled the service, or that the latest enablement placed; null before any enablement.",
      ),
    subscription_id: zod
      .uuid()
      .nullable()
      .describe(
        "The Billing subscription that requests are billed under; null before any enablement.",
      ),
    activated_at: zod.iso
      .datetime({ offset: true })
      .nullable()
      .describe("When the service became active and billing began; null until then."),
    ended_at: zod.iso
      .datetime({ offset: true })
      .nullable()
      .describe("When the subscription ended; null unless it has."),
  })
  .describe("The model platform service of a project.");

export type ServiceResource = zod.input<typeof ServiceResource>;
export type ServiceResourceOutput = zod.output<typeof ServiceResource>;
