/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pagination types
 * Shared pagination request parameters and response metadata. This document declares types only.
 *
 * The schemas here are referenced across documents. **The parameters are not**: a cross-document $ref to a
 * parameter does not survive the client generator, which emits a reference to a type that is never
 * produced — parameters do not become types. Copy a parameter into the document that uses it, as page and
 * page_size already are, and keep the wording identical.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const offsetPaginationTotalCountMin = 0;

export const OffsetPagination = zod
  .strictObject({
    page: zod.int().min(1),
    page_size: zod.int().min(1),
    total_count: zod.int().min(offsetPaginationTotalCountMin).optional(),
  })
  .describe(
    "Pagination metadata for stable numbered pages. total_count is returned only when the operation can determine it without an unbounded scan.",
  );

export type OffsetPagination = zod.input<typeof OffsetPagination>;
export type OffsetPaginationOutput = zod.output<typeof OffsetPagination>;
