/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Resource relationships
 * Resource claims, dependencies and reclamation policy. Types only.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { Attachment } from "./attachment.zod.js";
import { OffsetPagination } from "./offsetPagination.zod.js";

export const AttachmentList = zod.strictObject({
  items: zod.array(Attachment),
  pagination: OffsetPagination,
});

export type AttachmentList = zod.input<typeof AttachmentList>;
export type AttachmentListOutput = zod.output<typeof AttachmentList>;
