/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const Error = zod.strictObject({
  code: zod.string().optional(),
  message: zod.string(),
  meta: zod
    .record(zod.string(), zod.unknown())
    .optional()
    .describe(
      "What a given `code` carries alongside the message. The keys depend on the code,\nand a client that does not recognise one ignores it.",
    ),
  status: zod.int(),
});

export type Error = zod.input<typeof Error>;
export type ErrorOutput = zod.output<typeof Error>;
