/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const listProjectSubscriptionsParamsPageMax = 2147483647;

export const listProjectSubscriptionsParamsPageSizeMax = 100;

export const ListProjectSubscriptionsParams = zod.strictObject({
  expiring_before: zod.iso.datetime({ offset: true }).optional(),
  page: zod.int().min(1).max(listProjectSubscriptionsParamsPageMax).optional(),
  page_size: zod.int().min(1).max(listProjectSubscriptionsParamsPageSizeMax).optional(),
});

export type ListProjectSubscriptionsParams = zod.input<typeof ListProjectSubscriptionsParams>;
export type ListProjectSubscriptionsParamsOutput = zod.output<
  typeof ListProjectSubscriptionsParams
>;
