/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const listProjectActiveResourcesParamsPageMax = 2147483647;

export const listProjectActiveResourcesParamsPageSizeMax = 100;

export const ListProjectActiveResourcesParams = zod.strictObject({
  page: zod.int().min(1).max(listProjectActiveResourcesParamsPageMax).optional(),
  page_size: zod.int().min(1).max(listProjectActiveResourcesParamsPageSizeMax).optional(),
  resource_id: zod.string().optional(),
});

export type ListProjectActiveResourcesParams = zod.input<typeof ListProjectActiveResourcesParams>;
export type ListProjectActiveResourcesParamsOutput = zod.output<
  typeof ListProjectActiveResourcesParams
>;
