/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const listProjectOrderItemsParamsPageMax = 2147483647;

export const listProjectOrderItemsParamsPageSizeMax = 100;

export const ListProjectOrderItemsParams = zod.strictObject({
  page: zod.int().min(1).max(listProjectOrderItemsParamsPageMax).optional(),
  page_size: zod.int().min(1).max(listProjectOrderItemsParamsPageSizeMax).optional(),
});

export type ListProjectOrderItemsParams = zod.input<typeof ListProjectOrderItemsParams>;
export type ListProjectOrderItemsParamsOutput = zod.output<typeof ListProjectOrderItemsParams>;
