/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const Money = zod
  .string()
  .describe(
    "A decimal string, in the currency stated alongside it.\n\n**The currency is not part of this type.** It is carried by a `currency` field next to the\namount, or by the account the amount belongs to. Reading an amount without that field is\nreading a number with no unit.\n\nIt is a string rather than a JSON number because a JSON number is a float in most parsers,\nand a float loses precision on the first arithmetic. Nothing on this platform puts an amount\nthrough a float.",
  );

export type Money = zod.input<typeof Money>;
export type MoneyOutput = zod.output<typeof Money>;
