/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const quotedDiscountPromotionCodeMax = 64;

export const QuotedDiscount = zod
  .strictObject({
    type: zod.enum(["promotion_code", "account_discount"]),
    name: zod.string(),
    promotion_code: zod
      .string()
      .min(1)
      .max(quotedDiscountPromotionCodeMax)
      .nullable()
      .describe("Code text for a promotion_code discount; null for an account_discount."),
  })
  .describe(
    "The discount selected for this calculation. Its presence in a quote does not apply it or\nreserve a redemption. Discount amounts are reported on the quote and its lines.",
  );

export type QuotedDiscount = zod.input<typeof QuotedDiscount>;
export type QuotedDiscountOutput = zod.output<typeof QuotedDiscount>;
