/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { TerminationPolicy } from "./terminationPolicy.zod.js";

export const quoteCancellationSubscriptionIdsMax = 50;

export const QuoteCancellation = zod
  .strictObject({
    subscription_ids: zod
      .array(zod.uuid())
      .min(1)
      .max(quoteCancellationSubscriptionIdsMax)
      .describe(
        "The subscriptions to end together, all of one service. Every subscription released with a resource must be included.",
      ),
    mode: TerminationPolicy,
  })
  .describe(
    "A cancellation to quote: what ending these subscriptions together would return. One mode per\nrequest; to compare, quote `immediate` and `period_end` separately.",
  );

export type QuoteCancellation = zod.input<typeof QuoteCancellation>;
export type QuoteCancellationOutput = zod.output<typeof QuoteCancellation>;
