/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Project API
 * What one project has spent and bought, and the billing account linked to it.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const TerminationPolicy = zod
  .enum(["immediate", "period_end"])
  .describe(
    "Whether a fulfilled purchase may end immediately or only after its paid term. Does not grant a refund. When absent, the terms are not configured and termination requires review.",
  );

export type TerminationPolicy = zod.input<typeof TerminationPolicy>;
export type TerminationPolicyOutput = zod.output<typeof TerminationPolicy>;
