/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Checkout Types
 * Shared checkout choices for product purchases. Types only; this document declares no operations.
 * OpenAPI spec version: v1
 */

/**
 * automatic confirms checkout with applicable account discounts and collects payment from eligible
 * credit grants and available balance. Insufficient funds fail the purchase with HTTP 422
 * BILLING_INSUFFICIENT_FUNDS; no Billing order, charge or discount redemption is committed.
 * deferred creates a pending_checkout order for subsequent confirmation and payment through Billing.
 * No new discount redemption or payment is made when the order is created. An order whose total is
 * zero, with nothing to pay or discount, completes checkout at placement in either mode.
 */
export type CheckoutMode = (typeof CheckoutMode)[keyof typeof CheckoutMode];

export const CheckoutMode = {
  automatic: "automatic",
  deferred: "deferred",
} as const;
