// Code generated by ogen, DO NOT EDIT.

package billingv1server

// OperationName is the ogen operation name
type OperationName = string

const (
	BindProjectToBillingAccountOperation       OperationName = "BindProjectToBillingAccount"
	CancelSubscriptionOperation                OperationName = "CancelSubscription"
	CreateBillingAccountOperation              OperationName = "CreateBillingAccount"
	GetBillingAccountOperation                 OperationName = "GetBillingAccount"
	GetChargeUsageOperation                    OperationName = "GetChargeUsage"
	GetInvoiceOperation                        OperationName = "GetInvoice"
	GetOrderOperation                          OperationName = "GetOrder"
	KeepSubscriptionOperation                  OperationName = "KeepSubscription"
	ListBillingAccountsOperation               OperationName = "ListBillingAccounts"
	ListChargesOperation                       OperationName = "ListCharges"
	ListCreditTransactionsOperation            OperationName = "ListCreditTransactions"
	ListInvoicesOperation                      OperationName = "ListInvoices"
	ListOffersOperation                        OperationName = "ListOffers"
	ListOrdersOperation                        OperationName = "ListOrders"
	ListPaymentMethodsOperation                OperationName = "ListPaymentMethods"
	ListPrepaidAssetsOperation                 OperationName = "ListPrepaidAssets"
	ListTopUpsOperation                        OperationName = "ListTopUps"
	PurchaseOfferOperation                     OperationName = "PurchaseOffer"
	QuoteProjectUsageOperation                 OperationName = "QuoteProjectUsage"
	QuoteUsageOperation                        OperationName = "QuoteUsage"
	ReadBillingAccountBalanceOperation         OperationName = "ReadBillingAccountBalance"
	ReadBillingAccountBalanceMovementOperation OperationName = "ReadBillingAccountBalanceMovement"
	ReadProjectBillingAccountOperation         OperationName = "ReadProjectBillingAccount"
	ReadSubscriptionOperation                  OperationName = "ReadSubscription"
	ReadTopUpOperation                         OperationName = "ReadTopUp"
	RemovePaymentMethodOperation               OperationName = "RemovePaymentMethod"
	SetDefaultPaymentMethodOperation           OperationName = "SetDefaultPaymentMethod"
	StartPaymentMethodSetupOperation           OperationName = "StartPaymentMethodSetup"
	StartTopUpOperation                        OperationName = "StartTopUp"
	UnbindProjectFromBillingAccountOperation   OperationName = "UnbindProjectFromBillingAccount"
	UpdateBillingAccountOperation              OperationName = "UpdateBillingAccount"
)
