// Code generated by ogen, DO NOT EDIT.

package billingv1server

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// BindProjectToBillingAccount implements bind-project-to-billing-account operation.
	//
	// Binds a project to this account. A project bound to another account is moved.
	//
	// Both the account and the project must belong to the caller. Either one failing refuses the request.
	// Requiring the project as well as the account is what stops somebody attaching a project that is not
	// theirs — which sounds generous, since they would be paying for it, but it would also expose that
	// project's usage to them, and let them detach it again at any moment, leaving the project with no
	// account and therefore unable to allocate anything.
	//
	// Idempotent: binding a project already bound to this account changes nothing.
	//
	// Only subsequent usage is affected; see the hard constraint on rebinding.
	//
	// PUT /account/v1/billing-accounts/{accountKey}/projects/{projectId}
	BindProjectToBillingAccount(ctx context.Context, params BindProjectToBillingAccountParams) (*ProjectBinding, error)
	// CancelSubscription implements cancel-subscription operation.
	//
	// Takes the account off its paid plan and back to the free tier.
	//
	// Ending immediately lands on the free tier straight away. Ending at the end of the period is a plain
	// cancellation that can still be undone (`subscription/keep`) — it deliberately does not schedule a
	// switch, because a scheduled switch holds the customer's one subscription slot and the engine gives
	// no way to cancel it afterwards. The free tier is applied once the period actually ends, by the sweep
	// that keeps every account on some plan.
	//
	// `timing` has to be stated. Ending immediately on an account that has already paid for the current
	// period takes back what they paid for; ending at the end of the period does not. There is no default
	// because the two are materially different and picking one silently would make the wrong one happen
	// whenever the field is forgotten.
	//
	// Without this, someone who bought a paid plan can only stop paying by contacting support — which is
	// how a cancellation becomes a chargeback.
	//
	// POST /account/v1/billing-accounts/{accountKey}/subscription/cancel
	CancelSubscription(ctx context.Context, params CancelSubscriptionParams) (*Subscription, error)
	// CreateBillingAccount implements create-billing-account operation.
	//
	// Creates a billing account for the caller.
	//
	// `seq` is supplied by the client, not assigned here. Assigning it would mean reading the existing
	// accounts and adding one, which is a read-modify-write race: two concurrent "create" clicks compute
	// the same `seq`. Having the client name it turns that race into a plain idempotent repeat — the
	// second request returns the first account instead of failing.
	//
	// The new account pays for nothing. Binding a project is a separate, deliberate act; doing it here
	// would quietly turn "I want to add a card" into "I have changed who pays".
	//
	// POST /account/v1/billing-accounts
	CreateBillingAccount(ctx context.Context, req *CreateBillingAccountRequestBody) (*BillingAccount, error)
	// GetBillingAccount implements get-billing-account operation.
	//
	// One account, with the projects it currently pays for.
	//
	// The list returns the same objects, so this exists for the case the list cannot serve: a link
	// straight to one account. Making the caller fetch every account and filter turns a bookmarked page
	// into a request whose cost grows with how many accounts they hold.
	//
	// GET /account/v1/billing-accounts/{accountKey}
	GetBillingAccount(ctx context.Context, params GetBillingAccountParams) (*BillingAccount, error)
	// GetChargeUsage implements get-charge-usage operation.
	//
	// Splits one charge back into the projects that produced it, and lists the resources it could have
	// come from.
	//
	// # Why this is not a field on the charge
	//
	// A charge has no project, and that is not an omission: the billing subject is the account, and the
	// project is a dimension on each usage event. When three of an account's projects use the same
	// product, their usage aggregates into one charge — that charge genuinely spans three projects, and
	// stamping any single project id on it would be wrong.
	//
	// A split is also more useful than a label would be: it gives proportions, and proportions are what
	// decide which project's resources to switch off.
	//
	// # The quantity here is what was reported, not what was billed
	//
	// Conversion (machine-seconds to machine-hours) happens on the pricing side, and the engine does not
	// echo `unit_config` back on a charge. So this figure times the unit price does not equal the total
	// — a step is missing in between, and that step only becomes visible on the invoice, where the whole
	// pricing configuration is frozen onto each line.
	//
	// Reported quantity is still the right number for "which project is burning this", which is what the
	// split is for.
	//
	// # The resource list says which, not how much
	//
	// Usage events carry no resource id — it is not a grouping dimension, and making it one would mean
	// one time series per machine per hour. So the engine cannot attribute a charge to a machine. What it
	// can be attributed to is a product, and which resources of that product exist is something billing
	// knows from its own records.
	//
	// Destroyed resources are listed too: this period's charge includes the part they ran for. Leaving
	// them out is what makes the numbers fail to add up for someone who deleted a machine mid-month —
	// which is exactly the case they are trying to explain.
	//
	// # A flat fee answers with an empty split
	//
	// There is no meter behind it, so there is nothing to attribute. That is an answer, not an error.
	//
	// GET /account/v1/billing-accounts/{accountKey}/charges/{chargeId}/usage
	GetChargeUsage(ctx context.Context, params GetChargeUsageParams) (*ChargeUsage, error)
	// GetInvoice implements get-invoice operation.
	//
	// A total does not answer "why is it this much", and that is the question a bill provokes. Each line
	// carries its service period, without which lines of the same name — hundreds of them on an hourly
	// bill — cannot be told apart, and how much of it credit covered, which is the answer to "I have a
	// balance, why am I being charged".
	//
	// GET /account/v1/billing-accounts/{accountKey}/invoices/{invoiceId}
	GetInvoice(ctx context.Context, params GetInvoiceParams) (*InvoiceDetail, error)
	// GetOrder implements get-order operation.
	//
	// Each line names what was asked for, how much of it, and what it produced. The list route carries
	// lines too; this one exists for a permanent link to a single transaction.
	//
	// GET /account/v1/billing-accounts/{accountKey}/orders/{orderId}
	GetOrder(ctx context.Context, params GetOrderParams) (*Order, error)
	// KeepSubscription implements keep-subscription operation.
	//
	// Takes back a cancellation that was set for the end of the period, so the plan carries on.
	//
	// It only works on a cancellation, not on a scheduled downgrade. Scheduling a change to another plan
	// leaves a second, scheduled subscription holding the customer's one slot, and the engine offers no
	// way to remove it: unscheduling is refused with a conflict and the scheduled subscription cannot be
	// deleted over HTTP. So a downgrade becomes final the moment it is scheduled, and saying so up front
	// is the only honest thing to do — this endpoint answers `BILLING_NO_SCHEDULED_CHANGE` rather than
	// pretending to undo it.
	//
	// Without this, someone who cancels by accident has to wait out the period and buy the tier again,
	// losing whatever the tier had accumulated.
	//
	// POST /account/v1/billing-accounts/{accountKey}/subscription/keep
	KeepSubscription(ctx context.Context, params KeepSubscriptionParams) (*Subscription, error)
	// ListBillingAccounts implements list-billing-accounts operation.
	//
	// Every billing account belonging to the caller, with the projects each one currently pays for.
	//
	// Not paginated: how many accounts one person holds is bounded by how many they bothered to create,
	// and that is a small number.
	//
	// GET /account/v1/billing-accounts
	ListBillingAccounts(ctx context.Context, params ListBillingAccountsParams) (*BillingAccountList, error)
	// ListCharges implements list-charges operation.
	//
	// The itemised version of `unsettled`: what has been used this period and not yet billed.
	//
	// It has to come from charges rather than from invoices. An invoice only exists once a period has been
	// billed, and the one for the period in progress is in a state that does not appear in the invoice
	// list at all — reading invoices would show nothing and suggest the account has used nothing, while
	// the spend keeps climbing.
	//
	// GET /account/v1/billing-accounts/{accountKey}/charges
	ListCharges(ctx context.Context, params ListChargesParams) (*ChargeList, error)
	// ListCreditTransactions implements list-credit-transactions operation.
	//
	// Every movement of credit on this account: what was added, what was spent, what expired, what was
	// voided. Newest first.
	//
	// The balance on its own is a number with no account of itself. Asked why it is lower than expected,
	// it cannot answer, and the holder is left to guess between "I was charged" and "something expired"
	// — which lead to different next steps.
	//
	// GET /account/v1/billing-accounts/{accountKey}/credit-transactions
	ListCreditTransactions(ctx context.Context, params ListCreditTransactionsParams) (*CreditTransactionList, error)
	// ListInvoices implements list-invoices operation.
	//
	// Past periods, most recent first. The period in progress is not here — see the charges endpoint for
	// that.
	//
	// GET /account/v1/billing-accounts/{accountKey}/invoices
	ListInvoices(ctx context.Context, params ListInvoicesParams) (*InvoiceList, error)
	// ListOffers implements list-offers operation.
	//
	// Lists what is actually purchasable by this account, right now.
	//
	// # Every offer here has passed the full eligibility check
	//
	// The list is not "everything on sale" filtered by status. A promotion whose places are gone, a
	// first-month discount this person already used, a beta price they are not on the list for — none of
	// them appear. Returning them and rejecting the purchase afterwards reads as a broken system rather
	// than as a rule.
	//
	// The price is not here, and not because it was left out: an offer states who may buy, and when. What
	// it costs comes from the plan it points at, and is reported by the offers list.
	//
	// GET /account/v1/billing-accounts/{accountKey}/offers
	ListOffers(ctx context.Context, params ListOffersParams) (*OfferList, error)
	// ListOrders implements list-orders operation.
	//
	// Every provisioning request made against the projects this account pays for, newest first.
	//
	// An order that never went through stays here on purpose. Removing it would leave nothing to look at
	// in exactly the case someone wants to look: a resource was asked for, was not delivered, and the
	// question is what happened.
	//
	// Lines come with each order. A list showing only identifiers and amounts is a page nobody can read
	// — recognising one ("which of these was last week's machine") is why it gets opened.
	//
	// GET /account/v1/billing-accounts/{accountKey}/orders
	ListOrders(ctx context.Context, params ListOrdersParams) (*OrderList, error)
	// ListPaymentMethods implements list-payment-methods operation.
	//
	// Every method saved against this account, and which one an invoice will be charged to.
	//
	// # Why the brand, last four and expiry are here
	//
	// They were deliberately absent while the billing engine held the card, because the answer that
	// mattered — can money be collected — came from the engine, and a page built on the provider's
	// answer could show a method the engine had not recorded. Collection now runs from this service
	// against the provider directly, so there is one answer, and it is the one shown.
	//
	// Expiry is the reason this is worth showing at all: a card expires, the invoice then fails, dunning
	// runs out, and the project stops — with the account holder watching it happen and no indication
	// that a card was the cause.
	//
	// No other card data exists here. The number, the expiry entered by the holder and the CVC go from the
	// browser to the provider and never reach this platform.
	//
	// An account that has never added one returns an empty list. That is the normal state of a new
	// account, not an error.
	//
	// GET /account/v1/billing-accounts/{accountKey}/payment-methods
	ListPaymentMethods(ctx context.Context, params ListPaymentMethodsParams) (*PaymentMethodList, error)
	// ListPrepaidAssets implements list-prepaid-assets operation.
	//
	// Everything this account holds on a term, across every product.
	//
	// # Nothing here expires on its own
	//
	// A term renews for as long as the seat is held: the engine charges the next period, prorates any
	// change to the second, and stops the moment the seat is given up. So there is no renewal to remember
	// and no expiry to warn about — giving it up means deleting the resource, in the console that owns
	// it.
	//
	// What the next period costs and when it falls due is on the charges route. That is read straight from
	// the engine rather than copied here, because a copy is a second answer that drifts without saying so.
	//
	// # Metered resources are not here
	//
	// They have no term. Listing them would invite renewing something that is already billed by the hour
	// until it is deleted.
	//
	// # `state` and `desired_state` are both reported
	//
	// A machine stopped for arrears reads `suspended` for both. One being brought back reads `suspended`
	// and `active` — it is on its way. Without the second field those look identical, and a customer who
	// just paid concludes it did not work and pays again.
	//
	// GET /account/v1/billing-accounts/{accountKey}/prepaid-assets
	ListPrepaidAssets(ctx context.Context, params ListPrepaidAssetsParams) (*PrepaidAssetList, error)
	// ListTopUps implements list-top-ups operation.
	//
	// Every top-up this account has made, newest first.
	//
	// Reading one top-up requires already holding its identifier, and the only place that identifier
	// appears is the redirect that started it — so without this list a top-up becomes unfindable the
	// moment the browser tab is closed, which is exactly when somebody wants to check whether their money
	// arrived.
	//
	// GET /account/v1/billing-accounts/{accountKey}/top-ups
	ListTopUps(ctx context.Context, params ListTopUpsParams) (*TopUpList, error)
	// PurchaseOffer implements purchase-offer operation.
	//
	// Puts the account on the plan this offer points at, taking one of its places if it has a limit.
	//
	// # A card has to be on file first
	//
	// Unless the offer points at a free plan. A paid plan is collected from the card on file and refuses
	// to start the subscription without one; that refusal arrives here as a precondition error rather than
	// as a conflict.
	//
	// # `timing` is required only when the account already has a plan
	//
	// Moving between plans immediately is what an upgrade wants — the customer paid more and wants it
	// now. Waiting for the end of the period is what a downgrade wants — they already paid for this one.
	// Neither is a safe default, and picking one silently gets the money wrong whenever the field is
	// forgotten.
	//
	// # Being refused says which rule refused
	//
	// Places gone, window closed, already used, not on the list — each needs the customer to do
	// something different, and several of them need them to do nothing at all. A single "not eligible"
	// sends everyone to support.
	//
	// # Retrying is safe
	//
	// A place is taken before the subscription is created, so a failure in between leaves the place held
	// rather than the discount given away. Retrying the same purchase finishes it instead of taking a
	// second place.
	//
	// POST /account/v1/billing-accounts/{accountKey}/offers/{offerKey}/purchase
	PurchaseOffer(ctx context.Context, params PurchaseOfferParams) (*Purchase, error)
	// QuoteProjectUsage implements quote-project-usage operation.
	//
	// Prices a set of usages against whatever plan pays for this project, and returns every intermediate
	// step rather than a single number.
	//
	// # Why by project rather than by billing account
	//
	// The page that needs this is the one where somebody is about to create a machine, and all it has is a
	// project. Which account pays for that project is billing's own bookkeeping — asking the caller to
	// resolve it first would put that mapping into a page that otherwise has no business knowing accounts
	// exist.
	//
	// # Quantities are raw
	//
	// Seconds, token counts, GiB-seconds: the amount a service reports. Conversion happens here, which is
	// why services keep no conversion tables of their own and why the caller must not do the arithmetic
	// itself.
	//
	// Name each usage by `service` and `product_id` rather than by key: the key is a hash of a convention
	// that has exactly one implementation on purpose.
	//
	// # It is an estimate
	//
	// The engine computes the real amount; this reproduces the same rules. Every step comes back for that
	// reason — a single number that disagrees with the bill says nothing about which step was wrong.
	//
	// `404` means the project has no billing account, or its account is on no plan. Both are worth
	// showing: nothing can be created in either case, because admission refuses it.
	//
	// POST /account/v1/projects/{projectId}/quote
	QuoteProjectUsage(ctx context.Context, req *QuoteRequest, params QuoteProjectUsageParams) (*Quote, error)
	// QuoteUsage implements quote-usage operation.
	//
	// Prices a set of usages against whatever plan this account is currently on, and returns every
	// intermediate step rather than a single number.
	//
	// # What it is for
	//
	// Showing someone what a machine will cost before they create it. The console asks for the usage a
	// machine of that shape produces in an hour, and gets back what that hour costs them — on their
	// plan, with their discounts.
	//
	// # Quantities are raw
	//
	// Seconds, token counts, GiB-seconds: the amount a service reports. Conversion happens here, which is
	// why services keep no conversion tables of their own and why the console must not do the arithmetic
	// itself.
	//
	// # It is an estimate
	//
	// The engine computes the real amount; this reproduces the same rules. Every step comes back for that
	// reason — a single number that disagrees with the bill says nothing about which step was wrong.
	//
	// `404` means this account is not on any plan, and there is therefore nothing to price against.
	//
	// POST /account/v1/billing-accounts/{accountKey}/quote
	QuoteUsage(ctx context.Context, req *QuoteRequest, params QuoteUsageParams) (*Quote, error)
	// ReadBillingAccountBalance implements read-billing-account-balance operation.
	//
	// What is left on the account.
	//
	// The figure is the live balance: usage that has been reported but not yet settled is already
	// subtracted. The settled figure is larger, and the difference is precisely what the holder has just
	// spent — showing that instead would tell them they can afford something they cannot.
	//
	// An account that has never been topped up reports `"0"` — not an absent field, and not an empty
	// string.
	//
	// GET /account/v1/billing-accounts/{accountKey}/balance
	ReadBillingAccountBalance(ctx context.Context, params ReadBillingAccountBalanceParams) (*Balance, error)
	// ReadBillingAccountBalanceMovement implements read-billing-account-balance-movement operation.
	//
	// Opening balance, money in, money out, closing balance — for the current calendar month.
	//
	// The four add up: `closing = opening + income - spending`. That is the point of the endpoint. The
	// balance alone answers "how much is left" and cannot answer "how did it get there", which is what
	// somebody watching their balance shrink is actually asking. Four figures that add up can be checked
	// by the holder; a single figure can only be taken on faith or queried with support.
	//
	// `closing` is computed from the other three rather than read separately. Reading the current balance
	// for it would leave the equation off by whatever was booked between the two reads — and an equation
	// that is off by a few cents is worse than no equation, because it puts the ledger itself in doubt.
	//
	// The window is the calendar month, not the engine's billing period. This is the month a person means
	// when they say "this month"; the billing anchor is an internal recurrence that happens to line up.
	//
	// A month with no movement reports opening equal to closing and zero on both sides — not all zeroes,
	// which would read as "your money is gone".
	//
	// GET /account/v1/billing-accounts/{accountKey}/balance/movement
	ReadBillingAccountBalanceMovement(ctx context.Context, params ReadBillingAccountBalanceMovementParams) (*BalanceMovement, error)
	// ReadProjectBillingAccount implements read-project-billing-account operation.
	//
	// The account a project's resources are charged to, resolved from the project rather than guessed.
	//
	// # Why a console needs this
	//
	// Everything in a console happens inside a project, while billing accounts belong to a person — and
	// a person can have many. Showing "the first one" next to a sentence like you are overdrawn, new
	// resources will be refused pairs one account's balance with another account's rule. Both directions
	// are wrong and one of them is silent: the figures look healthy while creating anything is refused,
	// and the refusal names a reason the page just contradicted.
	//
	// # Being a member is enough to ask, but not to see the money
	//
	// The answer is the account's identity, not its balance. A project's members are not necessarily the
	// people paying for it — a company account can pay for a project someone else works in — and their
	// balance is not those members' business. Whoever owns the account reads the figures from the balance
	// route as before; `owned_by_me` says which case this is, so a page can tell "you are overdrawn" apart
	// from "ask whoever pays for this project".
	//
	// # A project with no account is a normal state, and it answers 404
	//
	// A project nobody has bound yet cannot create resources at all — admission refuses it. That is
	// worth saying plainly ("this project has no billing account, bind one") rather than falling back to
	// some other account of theirs, which is how the wrong-account problem started.
	//
	// GET /account/v1/projects/{projectId}/billing-account
	ReadProjectBillingAccount(ctx context.Context, params ReadProjectBillingAccountParams) (*ProjectBillingAccount, error)
	// ReadSubscription implements read-subscription operation.
	//
	// `404` means no plan, which is worth showing rather than hiding: an account without one is refused
	// admission, so nothing can be allocated in it.
	//
	// A subscription that has been cancelled but has not reached the end of its period still counts as
	// being on a plan — it is still serving, still billing, and the period has already been paid for.
	//
	// GET /account/v1/billing-accounts/{accountKey}/subscription
	ReadSubscription(ctx context.Context, params ReadSubscriptionParams) (*Subscription, error)
	// ReadTopUp implements read-top-up operation.
	//
	// Credit arrives asynchronously, shortly after the payment provider confirms the money. Coming back
	// from the payment page the balance has usually not moved yet, and without this there is no way to
	// tell "it is on its way" from "it failed" — the only recourse is refreshing the balance and
	// guessing.
	//
	// `settled` means the credit has landed. `pending` means the money arrived and the credit has not been
	// issued yet, or the payment method is an asynchronous one and the money itself is still in transit.
	//
	// GET /account/v1/billing-accounts/{accountKey}/top-ups/{paymentId}
	ReadTopUp(ctx context.Context, params ReadTopUpParams) (*TopUpStatus, error)
	// RemovePaymentMethod implements remove-payment-method operation.
	//
	// Detaches it from this account. Removing the last one is allowed.
	//
	// # Why removing the last one is not blocked
	//
	// Blocking it leaves an account holder who wants to stop paying with no way out. The cost of allowing
	// it is that later invoices cannot be collected — and that path has notice, a grace period and a way
	// back. A card that cannot be removed is a dead end.
	//
	// DELETE /account/v1/billing-accounts/{accountKey}/payment-methods/{paymentMethodId}
	RemovePaymentMethod(ctx context.Context, params RemovePaymentMethodParams) error
	// SetDefaultPaymentMethod implements set-default-payment-method operation.
	//
	// Makes this the method an invoice is collected from.
	//
	// # It is stored at the provider, not here
	//
	// The charge itself reads that setting from the provider, so keeping a second copy here would create
	// two answers to the same question. When they disagree the visible symptom is that the account holder
	// changed the default and the charge still went to the old one.
	//
	// PUT /account/v1/billing-accounts/{accountKey}/payment-methods/{paymentMethodId}/default
	SetDefaultPaymentMethod(ctx context.Context, params SetDefaultPaymentMethodParams) error
	// StartPaymentMethodSetup implements start-payment-method-setup operation.
	//
	// Starts a session for adding a method, and returns the secret the browser needs to mount the
	// provider's own form.
	//
	// # The form is embedded, not a redirect
	//
	// The returned `client_secret` initialises the provider's JavaScript, which renders its form inside an
	// iframe on this platform's own page. No card data reaches this platform — the number goes from the
	// browser straight to the provider, exactly as it would on a redirect — but the account holder never
	// leaves the console.
	//
	// A redirect would take them to a page with someone else's branding in the middle of adding a payment
	// method, which is the moment they are most likely to abandon it.
	//
	// # This is a prerequisite for buying a plan, not a convenience
	//
	// A plan is charged by invoice, and the invoice is collected from a method on file. Discovering that
	// none exists at purchase time turns a missing payment method into a rejection whose wording is about
	// something else entirely.
	//
	// It is not a prerequisite for topping up: a top-up collects the money there and then.
	//
	// POST /account/v1/billing-accounts/{accountKey}/payment-methods
	StartPaymentMethodSetup(ctx context.Context, params StartPaymentMethodSetupParams) (*PaymentMethodSetupSession, error)
	// StartTopUp implements start-top-up operation.
	//
	// Begins adding money to this account. Returns a URL to send the browser to; the card is entered
	// there, on the payment provider's own page.
	//
	// No card data ever reaches this platform, in any field, in any log. That is the entire reason this
	// returns a redirect instead of accepting card details.
	//
	// Credit is not added here. It is added once the payment provider confirms the money arrived, which
	// happens out of band and usually within seconds. The balance is unchanged when this call returns, and
	// polling it immediately will show the old figure.
	//
	// That ordering is deliberate. Credit is spendable as soon as it exists, so anything added before the
	// charge succeeds is money the holder can spend against a payment that then fails.
	//
	// Abandoning the page costs nothing; nothing is created on the account until the money arrives.
	//
	// POST /account/v1/billing-accounts/{accountKey}/top-ups
	StartTopUp(ctx context.Context, req *StartTopUpRequestBody, params StartTopUpParams) (*TopUpSession, error)
	// UnbindProjectFromBillingAccount implements unbind-project-from-billing-account operation.
	//
	// Unbinds the project from this account. Nothing pays for it afterwards, and everything in it is
	// refused admission until some account takes it on — no new machines, no forwarded requests.
	//
	// That consequence is the reason this exists rather than an argument against it: a project bound to
	// the wrong account has no other way out, and moving it to another of the caller's accounts is not a
	// correction when the answer is that this account should not be paying for it at all.
	//
	// Charges already accrued stay where they are. They were incurred while this account held the project,
	// and an invoice has to keep pointing at what it was based on.
	//
	// DELETE /account/v1/billing-accounts/{accountKey}/projects/{projectId}
	UnbindProjectFromBillingAccount(ctx context.Context, params UnbindProjectFromBillingAccountParams) error
	// UpdateBillingAccount implements update-billing-account operation.
	//
	// Changes the display name. Nothing else about the account can be changed here.
	//
	// The key is not among the fields and never will be: ownership is stated by the key, and invoices
	// already issued refer to it. The name is what tells two accounts apart in a list, so a mistake made
	// while creating one is otherwise permanent.
	//
	// PUT /account/v1/billing-accounts/{accountKey}
	UpdateBillingAccount(ctx context.Context, req *UpdateBillingAccountRequestBody, params UpdateBillingAccountParams) (*BillingAccount, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
