// Code generated by ogen, DO NOT EDIT.

package billingv1server

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerAuth handles bearerAuth security.
	// The account token: the one obtained by signing in at auth.leaflow.net. It says who you are and names
	// no project, which is what this API needs — a billing account belongs to a person, not to a
	// project. A project token is never accepted here.
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	BindProjectToBillingAccountOperation:       []string{},
	CancelSubscriptionOperation:                []string{},
	CreateBillingAccountOperation:              []string{},
	GetBillingAccountOperation:                 []string{},
	GetChargeUsageOperation:                    []string{},
	GetInvoiceOperation:                        []string{},
	GetOrderOperation:                          []string{},
	KeepSubscriptionOperation:                  []string{},
	ListBillingAccountsOperation:               []string{},
	ListChargesOperation:                       []string{},
	ListCreditTransactionsOperation:            []string{},
	ListInvoicesOperation:                      []string{},
	ListOffersOperation:                        []string{},
	ListOrdersOperation:                        []string{},
	ListPaymentMethodsOperation:                []string{},
	ListPrepaidAssetsOperation:                 []string{},
	ListTopUpsOperation:                        []string{},
	PurchaseOfferOperation:                     []string{},
	QuoteProjectUsageOperation:                 []string{},
	QuoteUsageOperation:                        []string{},
	ReadBillingAccountBalanceOperation:         []string{},
	ReadBillingAccountBalanceMovementOperation: []string{},
	ReadProjectBillingAccountOperation:         []string{},
	ReadSubscriptionOperation:                  []string{},
	ReadTopUpOperation:                         []string{},
	RemovePaymentMethodOperation:               []string{},
	SetDefaultPaymentMethodOperation:           []string{},
	StartPaymentMethodSetupOperation:           []string{},
	StartTopUpOperation:                        []string{},
	UnbindProjectFromBillingAccountOperation:   []string{},
	UpdateBillingAccountOperation:              []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearerAuth security value.
	// The account token: the one obtained by signing in at auth.leaflow.net. It says who you are and names
	// no project, which is what this API needs — a billing account belongs to a person, not to a
	// project. A project token is never accepted here.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
