// Code generated by ogen, DO NOT EDIT.

package billingv1server

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn7AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn2AllowedHeaders = map[string]string{
		"GET": "Authorization",
		"PUT": "Authorization,Content-Type",
	}
	rn37AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn38AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn17AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn10AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn19AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn20AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn12AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn22AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn31AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn23AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn14AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn25AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization",
	}
	rn45AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
	}
	rn46AllowedHeaders = map[string]string{
		"PUT": "Authorization",
	}
	rn27AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn4AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"PUT":    "Authorization",
	}
	rn36AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn41AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn6AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn16AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn28AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn43AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn40AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn35AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/account/v1/"

			if l := len("/account/v1/"); len(elem) >= l && elem[0:l] == "/account/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'b': // Prefix: "billing-accounts"

				if l := len("billing-accounts"); len(elem) >= l && elem[0:l] == "billing-accounts" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListBillingAccountsRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateBillingAccountRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn7AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "accountKey"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetBillingAccountRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateBillingAccountRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,PUT",
								allowedHeaders: rn2AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'b': // Prefix: "balance"

							if l := len("balance"); len(elem) >= l && elem[0:l] == "balance" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleReadBillingAccountBalanceRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn37AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/movement"

								if l := len("/movement"); len(elem) >= l && elem[0:l] == "/movement" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleReadBillingAccountBalanceMovementRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn38AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'c': // Prefix: "c"

							if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'h': // Prefix: "harges"

								if l := len("harges"); len(elem) >= l && elem[0:l] == "harges" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleListChargesRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn17AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "chargeId"
									// Match until "/"
									idx := strings.IndexByte(elem, '/')
									if idx < 0 {
										idx = len(elem)
									}
									args[1] = elem[:idx]
									elem = elem[idx:]

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case '/': // Prefix: "/usage"

										if l := len("/usage"); len(elem) >= l && elem[0:l] == "/usage" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "GET":
												s.handleGetChargeUsageRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "GET",
													allowedHeaders: rn10AllowedHeaders,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}

									}

								}

							case 'r': // Prefix: "redit-transactions"

								if l := len("redit-transactions"); len(elem) >= l && elem[0:l] == "redit-transactions" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleListCreditTransactionsRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn19AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'i': // Prefix: "invoices"

							if l := len("invoices"); len(elem) >= l && elem[0:l] == "invoices" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListInvoicesRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn20AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "invoiceId"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleGetInvoiceRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn12AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'o': // Prefix: "o"

							if l := len("o"); len(elem) >= l && elem[0:l] == "o" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'f': // Prefix: "ffers"

								if l := len("ffers"); len(elem) >= l && elem[0:l] == "ffers" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleListOffersRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn22AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "offerKey"
									// Match until "/"
									idx := strings.IndexByte(elem, '/')
									if idx < 0 {
										idx = len(elem)
									}
									args[1] = elem[:idx]
									elem = elem[idx:]

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case '/': // Prefix: "/purchase"

										if l := len("/purchase"); len(elem) >= l && elem[0:l] == "/purchase" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "POST":
												s.handlePurchaseOfferRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "POST",
													allowedHeaders: rn31AllowedHeaders,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}

									}

								}

							case 'r': // Prefix: "rders"

								if l := len("rders"); len(elem) >= l && elem[0:l] == "rders" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleListOrdersRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn23AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "orderId"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "GET":
											s.handleGetOrderRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET",
												allowedHeaders: rn14AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							}

						case 'p': // Prefix: "p"

							if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'a': // Prefix: "ayment-methods"

								if l := len("ayment-methods"); len(elem) >= l && elem[0:l] == "ayment-methods" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleListPaymentMethodsRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									case "POST":
										s.handleStartPaymentMethodSetupRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET,POST",
											allowedHeaders: rn25AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "paymentMethodId"
									// Match until "/"
									idx := strings.IndexByte(elem, '/')
									if idx < 0 {
										idx = len(elem)
									}
									args[1] = elem[:idx]
									elem = elem[idx:]

									if len(elem) == 0 {
										switch r.Method {
										case "DELETE":
											s.handleRemovePaymentMethodRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "DELETE",
												allowedHeaders: rn45AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}
									switch elem[0] {
									case '/': // Prefix: "/default"

										if l := len("/default"); len(elem) >= l && elem[0:l] == "/default" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "PUT":
												s.handleSetDefaultPaymentMethodRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "PUT",
													allowedHeaders: rn46AllowedHeaders,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}

									}

								}

							case 'r': // Prefix: "r"

								if l := len("r"); len(elem) >= l && elem[0:l] == "r" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'e': // Prefix: "epaid-assets"

									if l := len("epaid-assets"); len(elem) >= l && elem[0:l] == "epaid-assets" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "GET":
											s.handleListPrepaidAssetsRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET",
												allowedHeaders: rn27AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								case 'o': // Prefix: "ojects/"

									if l := len("ojects/"); len(elem) >= l && elem[0:l] == "ojects/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "projectId"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "DELETE":
											s.handleUnbindProjectFromBillingAccountRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										case "PUT":
											s.handleBindProjectToBillingAccountRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "DELETE,PUT",
												allowedHeaders: rn4AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							}

						case 'q': // Prefix: "quote"

							if l := len("quote"); len(elem) >= l && elem[0:l] == "quote" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleQuoteUsageRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn36AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 's': // Prefix: "subscription"

							if l := len("subscription"); len(elem) >= l && elem[0:l] == "subscription" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleReadSubscriptionRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn41AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'c': // Prefix: "cancel"

									if l := len("cancel"); len(elem) >= l && elem[0:l] == "cancel" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleCancelSubscriptionRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn6AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								case 'k': // Prefix: "keep"

									if l := len("keep"); len(elem) >= l && elem[0:l] == "keep" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleKeepSubscriptionRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn16AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							}

						case 't': // Prefix: "top-ups"

							if l := len("top-ups"); len(elem) >= l && elem[0:l] == "top-ups" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListTopUpsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleStartTopUpRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn28AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "paymentId"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleReadTopUpRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn43AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					}

				}

			case 'p': // Prefix: "projects/"

				if l := len("projects/"); len(elem) >= l && elem[0:l] == "projects/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "projectId"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'b': // Prefix: "billing-account"

						if l := len("billing-account"); len(elem) >= l && elem[0:l] == "billing-account" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleReadProjectBillingAccountRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn40AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'q': // Prefix: "quote"

						if l := len("quote"); len(elem) >= l && elem[0:l] == "quote" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleQuoteProjectUsageRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn35AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/account/v1/"

			if l := len("/account/v1/"); len(elem) >= l && elem[0:l] == "/account/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'b': // Prefix: "billing-accounts"

				if l := len("billing-accounts"); len(elem) >= l && elem[0:l] == "billing-accounts" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListBillingAccountsOperation
						r.summary = "List my billing accounts"
						r.operationID = "list-billing-accounts"
						r.operationGroup = ""
						r.pathPattern = "/account/v1/billing-accounts"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateBillingAccountOperation
						r.summary = "Create a billing account"
						r.operationID = "create-billing-account"
						r.operationGroup = ""
						r.pathPattern = "/account/v1/billing-accounts"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "accountKey"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetBillingAccountOperation
							r.summary = "Read one of my billing accounts"
							r.operationID = "get-billing-account"
							r.operationGroup = ""
							r.pathPattern = "/account/v1/billing-accounts/{accountKey}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateBillingAccountOperation
							r.summary = "Rename a billing account"
							r.operationID = "update-billing-account"
							r.operationGroup = ""
							r.pathPattern = "/account/v1/billing-accounts/{accountKey}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'b': // Prefix: "balance"

							if l := len("balance"); len(elem) >= l && elem[0:l] == "balance" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ReadBillingAccountBalanceOperation
									r.summary = "Read an account's balance"
									r.operationID = "read-billing-account-balance"
									r.operationGroup = ""
									r.pathPattern = "/account/v1/billing-accounts/{accountKey}/balance"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/movement"

								if l := len("/movement"); len(elem) >= l && elem[0:l] == "/movement" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ReadBillingAccountBalanceMovementOperation
										r.summary = "How the balance moved this month"
										r.operationID = "read-billing-account-balance-movement"
										r.operationGroup = ""
										r.pathPattern = "/account/v1/billing-accounts/{accountKey}/balance/movement"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 'c': // Prefix: "c"

							if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'h': // Prefix: "harges"

								if l := len("harges"); len(elem) >= l && elem[0:l] == "harges" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = ListChargesOperation
										r.summary = "What this period has run up so far"
										r.operationID = "list-charges"
										r.operationGroup = ""
										r.pathPattern = "/account/v1/billing-accounts/{accountKey}/charges"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "chargeId"
									// Match until "/"
									idx := strings.IndexByte(elem, '/')
									if idx < 0 {
										idx = len(elem)
									}
									args[1] = elem[:idx]
									elem = elem[idx:]

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case '/': // Prefix: "/usage"

										if l := len("/usage"); len(elem) >= l && elem[0:l] == "/usage" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "GET":
												r.name = GetChargeUsageOperation
												r.summary = "What produced this charge"
												r.operationID = "get-charge-usage"
												r.operationGroup = ""
												r.pathPattern = "/account/v1/billing-accounts/{accountKey}/charges/{chargeId}/usage"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

									}

								}

							case 'r': // Prefix: "redit-transactions"

								if l := len("redit-transactions"); len(elem) >= l && elem[0:l] == "redit-transactions" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ListCreditTransactionsOperation
										r.summary = "How the balance got to where it is"
										r.operationID = "list-credit-transactions"
										r.operationGroup = ""
										r.pathPattern = "/account/v1/billing-accounts/{accountKey}/credit-transactions"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 'i': // Prefix: "invoices"

							if l := len("invoices"); len(elem) >= l && elem[0:l] == "invoices" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListInvoicesOperation
									r.summary = "List this account's invoices"
									r.operationID = "list-invoices"
									r.operationGroup = ""
									r.pathPattern = "/account/v1/billing-accounts/{accountKey}/invoices"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "invoiceId"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = GetInvoiceOperation
										r.summary = "Read one invoice with its lines"
										r.operationID = "get-invoice"
										r.operationGroup = ""
										r.pathPattern = "/account/v1/billing-accounts/{accountKey}/invoices/{invoiceId}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							}

						case 'o': // Prefix: "o"

							if l := len("o"); len(elem) >= l && elem[0:l] == "o" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'f': // Prefix: "ffers"

								if l := len("ffers"); len(elem) >= l && elem[0:l] == "ffers" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = ListOffersOperation
										r.summary = "List the offers this account can buy"
										r.operationID = "list-offers"
										r.operationGroup = ""
										r.pathPattern = "/account/v1/billing-accounts/{accountKey}/offers"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "offerKey"
									// Match until "/"
									idx := strings.IndexByte(elem, '/')
									if idx < 0 {
										idx = len(elem)
									}
									args[1] = elem[:idx]
									elem = elem[idx:]

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case '/': // Prefix: "/purchase"

										if l := len("/purchase"); len(elem) >= l && elem[0:l] == "/purchase" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "POST":
												r.name = PurchaseOfferOperation
												r.summary = "Buy an offer"
												r.operationID = "purchase-offer"
												r.operationGroup = ""
												r.pathPattern = "/account/v1/billing-accounts/{accountKey}/offers/{offerKey}/purchase"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

									}

								}

							case 'r': // Prefix: "rders"

								if l := len("rders"); len(elem) >= l && elem[0:l] == "rders" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = ListOrdersOperation
										r.summary = "My orders"
										r.operationID = "list-orders"
										r.operationGroup = ""
										r.pathPattern = "/account/v1/billing-accounts/{accountKey}/orders"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "orderId"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "GET":
											r.name = GetOrderOperation
											r.summary = "One order, with its lines"
											r.operationID = "get-order"
											r.operationGroup = ""
											r.pathPattern = "/account/v1/billing-accounts/{accountKey}/orders/{orderId}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								}

							}

						case 'p': // Prefix: "p"

							if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'a': // Prefix: "ayment-methods"

								if l := len("ayment-methods"); len(elem) >= l && elem[0:l] == "ayment-methods" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = ListPaymentMethodsOperation
										r.summary = "The payment methods on file"
										r.operationID = "list-payment-methods"
										r.operationGroup = ""
										r.pathPattern = "/account/v1/billing-accounts/{accountKey}/payment-methods"
										r.args = args
										r.count = 1
										return r, true
									case "POST":
										r.name = StartPaymentMethodSetupOperation
										r.summary = "Begin adding a payment method"
										r.operationID = "start-payment-method-setup"
										r.operationGroup = ""
										r.pathPattern = "/account/v1/billing-accounts/{accountKey}/payment-methods"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "paymentMethodId"
									// Match until "/"
									idx := strings.IndexByte(elem, '/')
									if idx < 0 {
										idx = len(elem)
									}
									args[1] = elem[:idx]
									elem = elem[idx:]

									if len(elem) == 0 {
										switch method {
										case "DELETE":
											r.name = RemovePaymentMethodOperation
											r.summary = "Remove a payment method"
											r.operationID = "remove-payment-method"
											r.operationGroup = ""
											r.pathPattern = "/account/v1/billing-accounts/{accountKey}/payment-methods/{paymentMethodId}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}
									switch elem[0] {
									case '/': // Prefix: "/default"

										if l := len("/default"); len(elem) >= l && elem[0:l] == "/default" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "PUT":
												r.name = SetDefaultPaymentMethodOperation
												r.summary = "Charge invoices to this one"
												r.operationID = "set-default-payment-method"
												r.operationGroup = ""
												r.pathPattern = "/account/v1/billing-accounts/{accountKey}/payment-methods/{paymentMethodId}/default"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

									}

								}

							case 'r': // Prefix: "r"

								if l := len("r"); len(elem) >= l && elem[0:l] == "r" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'e': // Prefix: "epaid-assets"

									if l := len("epaid-assets"); len(elem) >= l && elem[0:l] == "epaid-assets" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "GET":
											r.name = ListPrepaidAssetsOperation
											r.summary = "What I bought outright"
											r.operationID = "list-prepaid-assets"
											r.operationGroup = ""
											r.pathPattern = "/account/v1/billing-accounts/{accountKey}/prepaid-assets"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								case 'o': // Prefix: "ojects/"

									if l := len("ojects/"); len(elem) >= l && elem[0:l] == "ojects/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "projectId"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "DELETE":
											r.name = UnbindProjectFromBillingAccountOperation
											r.summary = "Stop paying for a project"
											r.operationID = "unbind-project-from-billing-account"
											r.operationGroup = ""
											r.pathPattern = "/account/v1/billing-accounts/{accountKey}/projects/{projectId}"
											r.args = args
											r.count = 2
											return r, true
										case "PUT":
											r.name = BindProjectToBillingAccountOperation
											r.summary = "Make this account pay for a project"
											r.operationID = "bind-project-to-billing-account"
											r.operationGroup = ""
											r.pathPattern = "/account/v1/billing-accounts/{accountKey}/projects/{projectId}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								}

							}

						case 'q': // Prefix: "quote"

							if l := len("quote"); len(elem) >= l && elem[0:l] == "quote" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = QuoteUsageOperation
									r.summary = "What a usage would cost on this account's plan"
									r.operationID = "quote-usage"
									r.operationGroup = ""
									r.pathPattern = "/account/v1/billing-accounts/{accountKey}/quote"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "subscription"

							if l := len("subscription"); len(elem) >= l && elem[0:l] == "subscription" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ReadSubscriptionOperation
									r.summary = "Which plan this account is on"
									r.operationID = "read-subscription"
									r.operationGroup = ""
									r.pathPattern = "/account/v1/billing-accounts/{accountKey}/subscription"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'c': // Prefix: "cancel"

									if l := len("cancel"); len(elem) >= l && elem[0:l] == "cancel" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = CancelSubscriptionOperation
											r.summary = "Come off the paid plan"
											r.operationID = "cancel-subscription"
											r.operationGroup = ""
											r.pathPattern = "/account/v1/billing-accounts/{accountKey}/subscription/cancel"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								case 'k': // Prefix: "keep"

									if l := len("keep"); len(elem) >= l && elem[0:l] == "keep" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = KeepSubscriptionOperation
											r.summary = "Undo an end-of-period cancellation"
											r.operationID = "keep-subscription"
											r.operationGroup = ""
											r.pathPattern = "/account/v1/billing-accounts/{accountKey}/subscription/keep"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								}

							}

						case 't': // Prefix: "top-ups"

							if l := len("top-ups"); len(elem) >= l && elem[0:l] == "top-ups" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListTopUpsOperation
									r.summary = "My top-ups"
									r.operationID = "list-top-ups"
									r.operationGroup = ""
									r.pathPattern = "/account/v1/billing-accounts/{accountKey}/top-ups"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = StartTopUpOperation
									r.summary = "Start a top-up"
									r.operationID = "start-top-up"
									r.operationGroup = ""
									r.pathPattern = "/account/v1/billing-accounts/{accountKey}/top-ups"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "paymentId"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ReadTopUpOperation
										r.summary = "How far along a top-up is"
										r.operationID = "read-top-up"
										r.operationGroup = ""
										r.pathPattern = "/account/v1/billing-accounts/{accountKey}/top-ups/{paymentId}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							}

						}

					}

				}

			case 'p': // Prefix: "projects/"

				if l := len("projects/"); len(elem) >= l && elem[0:l] == "projects/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "projectId"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'b': // Prefix: "billing-account"

						if l := len("billing-account"); len(elem) >= l && elem[0:l] == "billing-account" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = ReadProjectBillingAccountOperation
								r.summary = "Which account pays for this project"
								r.operationID = "read-project-billing-account"
								r.operationGroup = ""
								r.pathPattern = "/account/v1/projects/{projectId}/billing-account"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					case 'q': // Prefix: "quote"

						if l := len("quote"); len(elem) >= l && elem[0:l] == "quote" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = QuoteProjectUsageOperation
								r.summary = "What a usage would cost in this project"
								r.operationID = "quote-project-usage"
								r.operationGroup = ""
								r.pathPattern = "/account/v1/projects/{projectId}/quote"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			}

		}
	}
	return r, false
}
