/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Account API
 * Everything that comes before a project is chosen: registration, the account itself, the projects the caller belongs to, and entry into one of them.
 *
 * ## Authentication
 *
 * Every request carries `Authorization: Bearer <access token>`, obtained by signing in at auth.leaflow.net. The endpoints that need no token say so.
 *
 * ## Entering a project
 *
 * 1. `GET /account/v1/projects` lists the projects the caller belongs to. The first call registers the account, taking the name and email address from the sign-in claims.
 * 2. `POST /account/v1/projects/{projectId}/scoped-tokens` returns a scoped token for the project chosen.
 * 3. Every other service is called with that scoped token.
 *
 * A scoped token cannot be renewed. Repeat step 2 for a new one, and sign in again at auth.leaflow.net once the access token itself has expired.
 * OpenAPI spec version: 1.0.0
 */
import type { ConsentBody } from "./consentBody.js";
import type { Locale } from "./locale.js";

export interface RegisterRequestBody {
  /**
   * Must cover every agreement currently in force, at the versions returned by GET /account/v1/agreements
   * @nullable
   */
  consents: ConsentBody[] | null;
  /**
   * ISO 3166-1 alpha-2 (CN, HK, US). Must denote a country or territory that exists; codes such as EU and ZZ hold a place in the standard without denoting one and are refused
   * @minLength 2
   * @maxLength 2
   */
  country: string;
  locale: Locale;
}
