/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow IAM API
 * What happens inside a project: members, roles, invitations and SSH keys.
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme. No path carries a
 * `projectId`, and the current project is the one the token states. Tokens are obtained from the
 * account API.
 *
 * `GET /api/v1/membership` returns the roles and permissions the caller holds in the current
 * project. It does not state whether a given operation is allowed; each service declares which permission its own operations require.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSSHKeyRequestBodyOwner } from "./createSSHKeyRequestBodyOwner.js";

export interface CreateSSHKeyRequestBody {
  /**
   * @minLength 1
   * @maxLength 128
   */
  name: string;
  /** Who this key belongs to */
  owner?: CreateSSHKeyRequestBodyOwner;
  /**
   * The public key in OpenSSH format. The type and the fingerprint are derived from it and cannot be changed
   * @minLength 1
   * @maxLength 16384
   */
  public_key: string;
  /**
   * A purpose label, such as ci or bastion
   * @maxItems 16
   * @nullable
   */
  purposes?: string[] | null;
}
