/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow IAM API
 * What happens inside a project: members, roles, invitations and SSH keys.
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme. No path carries a
 * `projectId`, and the current project is the one the token states. Tokens are obtained from the
 * account API.
 *
 * `GET /api/v1/membership` returns the roles and permissions the caller holds in the current
 * project. It does not state whether a given operation is allowed; each service declares which permission its own operations require.
 * OpenAPI spec version: 1.0.0
 */
import type { ListSshKeysStatus } from "./listSshKeysStatus.js";

export type ListSshKeysParams = {
  /**
   * Maximum number of items in this page
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * Number of items to skip. Use the cursor-paged endpoint to page deeper
   * @minimum 0
   * @maximum 10000
   */
  offset?: number;
  /**
   * Both kinds are returned while this is absent
   */
  status?: ListSshKeysStatus;
  /**
   * Lists only the keys carrying this purpose. The key the platform generates carries `platform`
   * @maxLength 64
   */
  purpose?: string;
};
