/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow IAM API
 * What happens inside a project: members, roles, invitations and SSH keys.
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme. No path carries a
 * `projectId`, and the current project is the one the token states. Tokens are obtained from the
 * account API.
 *
 * `GET /api/v1/membership` returns the roles and permissions the caller holds in the current
 * project. It does not state whether a given operation is allowed; each service declares which permission its own operations require.
 * OpenAPI spec version: 1.0.0
 */
import type { PolicyResourceEffect } from "./policyResourceEffect.js";
import type { ResourceRefResource } from "./resourceRefResource.js";

export interface PolicyResource {
  /** The base policy is the one whose effect is `allow` and which covers every resource. Each member holds exactly one, and it carries their ordinary roles. Change it with PUT /members/{userId}/roles and PUT /members/{userId}/permissions */
  base: boolean;
  created_at: string;
  /** Why it was granted, written for a reader */
  description: string;
  effect: PolicyResourceEffect;
  id: string;
  /**
   * Permission names attached directly to this person, without passing through a role
   * @nullable
   */
  permissions: string[] | null;
  /**
   * Empty means the whole project
   * @nullable
   */
  resources: ResourceRefResource[] | null;
  /**
   * The role codes this policy carries
   * @nullable
   */
  roles: string[] | null;
  updated_at: string;
  user_id: string;
}
