/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Order Types
 * Order references returned by product purchases. Types only; this document declares no operations.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const PlacedOrder = zod
  .strictObject({
    invoice_id: zod
      .uuid()
      .nullable()
      .describe(
        "The invoice for this purchase, which may still be a draft awaiting checkout. Null when no invoice has been created. Its presence or absence does not establish whether delivery may begin.",
      ),
    order_id: zod
      .uuid()
      .describe(
        "The order, including for purchases without an immediate charge. Payment alone does not imply that the service has completed delivery.",
      ),
  })
  .describe(
    "Identifies the purchase. Read the order for purchase progress and its invoice for amounts and payment status.",
  );

export type PlacedOrder = zod.input<typeof PlacedOrder>;
export type PlacedOrderOutput = zod.output<typeof PlacedOrder>;
