/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Catalog API
 * What the platform sells and what it costs: services, sellable plans, prices, shared rate
 * cards and estimates. No credentials are required.
 * OpenAPI spec version: 1.0.0
 */

/**
 * A decimal string, in the currency stated alongside it.
 *
 * **The currency is not part of this type.** It is carried by a `currency` field next to the
 * amount, or by the account the amount belongs to. Reading an amount without that field is
 * reading a number with no unit.
 *
 * It is a string rather than a JSON number because a JSON number is a float in most parsers,
 * and a float loses precision on the first arithmetic. Nothing on this platform puts an amount
 * through a float.
 */
export type Money = string;
