/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Catalog API
 * What the platform sells and what it costs: services, sellable plans, prices, shared rate
 * cards and estimates. No credentials are required.
 * OpenAPI spec version: 1.0.0
 */

/**
 * `postpaid` charges for what is used, `prepaid` buys a period in advance, `one_time`
 * charges once.
 */
export type PriceType = (typeof PriceType)[keyof typeof PriceType];

export const PriceType = {
  postpaid: "postpaid",
  prepaid: "prepaid",
  one_time: "one_time",
} as const;
