/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Catalog API
 * What the platform sells and what it costs: services, sellable plans, prices, shared rate
 * cards and estimates. No credentials are required.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Immutable platform service identifier, such as compute, canopy or assistant.
 * @minLength 1
 * @maxLength 64
 * @pattern ^[a-z][a-z0-9]*(-[a-z0-9]+)*$
 */
export type ProductID = string;
