/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Catalog API
 * What the platform sells and what it costs: services, sellable plans, prices, shared rate
 * cards and estimates. No credentials are required.
 * OpenAPI spec version: 1.0.0
 */
import type { Money } from "./money.js";
import type { QuotedLine } from "./quotedLine.js";

/**
 * A public catalog estimate. No account discounts or tax are evaluated. Its total is a list-price
 * estimate, not an expected checkout amount. Nothing is saved, charged or reserved.
 */
export interface Quote {
  lines?: QuotedLine[];
  /**
   * Sum of the public list-price line amounts, without evaluating account discounts or tax.
   *
   * Null when any line could not be priced. What would be owed is not knowable then, and a
   * total that silently left the unpriced lines out would read as a smaller bill rather than
   * an incomplete one — the per-line `priced` flag is easy to skip, a missing total is not.
   */
  total?: Money | null;
  currency: string;
}
