/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Catalog API
 * What the platform sells and what it costs: services, sellable plans, prices, shared rate
 * cards and estimates. No credentials are required.
 * OpenAPI spec version: 1.0.0
 */

export type RatePricingModel = (typeof RatePricingModel)[keyof typeof RatePricingModel];

export const RatePricingModel = {
  per_unit: "per_unit",
  graduated: "graduated",
  volume: "volume",
} as const;
