/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Catalog API
 * What the platform sells and what it costs: services, sellable plans, prices, shared rate
 * cards and estimates. No credentials are required.
 * OpenAPI spec version: 1.0.0
 */
import type { Money } from "./money.js";
import type { ObjectIdentity } from "./objectIdentity.js";
import type { RateDimensions } from "./rateDimensions.js";
import type { RatePricingModel } from "./ratePricingModel.js";
import type { Tier } from "./tier.js";

export interface Rate {
  meter: ObjectIdentity;
  /** The unit readings arrive in, such as `core-second`. */
  unit?: string;
  /** The attributes this rate applies to, such as region and machine type. */
  dimensions: RateDimensions;
  pricing_model: RatePricingModel;
  /** Present for `per_unit`. Tiered rates carry their amounts on the tiers. */
  unit_amount?: Money;
  /** Present for `graduated` and `volume`, in ascending order. */
  tiers?: Tier[];
  /**
   * How many measured units one amount covers. An hourly rate on a per-second meter is
   * `"3600"`.
   */
  unit_quantity?: string;
  currency: string;
  effective_from: string;
  /** @nullable */
  effective_to?: string | null;
}
