/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Catalog API
 * What the platform sells and what it costs: services, sellable plans, prices, shared rate
 * cards and estimates. No credentials are required.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Whether a fulfilled purchase may end immediately or only after its paid term. Does not grant a refund. When absent, the terms are not configured and termination requires review.
 */
export type TerminationPolicy = (typeof TerminationPolicy)[keyof typeof TerminationPolicy];

export const TerminationPolicy = {
  immediate: "immediate",
  period_end: "period_end",
} as const;
