/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow IAM API
 * What happens inside a project: members, roles, invitations and SSH keys.
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme. No path carries a
 * `projectId`, and the current project is the one the token states. Tokens are obtained from the
 * account API.
 *
 * `GET /api/v1/membership` returns the roles and permissions the caller holds in the current
 * project. It does not state whether a given operation is allowed; each service declares which permission its own operations require.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { ResolvedMemberResource } from "./resolvedMemberResource.zod.js";

export const BatchGetMembersResponseBody = zod.strictObject({
  items: zod
    .array(ResolvedMemberResource)
    .describe(
      "The people that resolved. Ids that never belonged to this project are absent, as are ids that do not resolve at all.",
    ),
});

export type BatchGetMembersResponseBody = zod.input<typeof BatchGetMembersResponseBody>;
export type BatchGetMembersResponseBodyOutput = zod.output<typeof BatchGetMembersResponseBody>;
