/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow IAM API
 * What happens inside a project: members, roles, invitations and SSH keys.
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme. No path carries a
 * `projectId`, and the current project is the one the token states. Tokens are obtained from the
 * account API.
 *
 * `GET /api/v1/membership` returns the roles and permissions the caller holds in the current
 * project. It does not state whether a given operation is allowed; each service declares which permission its own operations require.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const createRoleRequestBodyCodeMax = 64;

export const createRoleRequestBodyDescriptionMax = 255;

export const createRoleRequestBodyNameMax = 64;

export const CreateRoleRequestBody = zod.strictObject({
  code: zod
    .string()
    .min(1)
    .max(createRoleRequestBodyCodeMax)
    .describe(
      "Begins with a lower-case letter and may contain digits and underscores. It cannot be changed once created, as member bindings and invitations refer to it",
    ),
  description: zod.string().max(createRoleRequestBodyDescriptionMax).optional(),
  name: zod.string().min(1).max(createRoleRequestBodyNameMax),
  permissions: zod
    .array(zod.string())
    .nullish()
    .describe(
      "A permission name. The ones reserved for the owner are refused, since attaching them would have no effect",
    ),
});

export type CreateRoleRequestBody = zod.input<typeof CreateRoleRequestBody>;
export type CreateRoleRequestBodyOutput = zod.output<typeof CreateRoleRequestBody>;
