/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow IAM API
 * What happens inside a project: members, roles, invitations and SSH keys.
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme. No path carries a
 * `projectId`, and the current project is the one the token states. Tokens are obtained from the
 * account API.
 *
 * `GET /api/v1/membership` returns the roles and permissions the caller holds in the current
 * project. It does not state whether a given operation is allowed; each service declares which permission its own operations require.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { RuleResource } from "./ruleResource.zod.js";

export const GrantResource = zod.strictObject({
  admin: zod.boolean(),
  owner: zod.boolean(),
  roles: zod.array(zod.string()).nullable().describe("The role codes held, for display only"),
  rules: zod
    .array(RuleResource)
    .nullable()
    .describe(
      "**The rules compiled from every policy that applies. Do not walk them to reach a decision.** They are here to render what a user may do; each request is decided by the service handling it",
    ),
});

export type GrantResource = zod.input<typeof GrantResource>;
export type GrantResourceOutput = zod.output<typeof GrantResource>;
