/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow IAM API
 * What happens inside a project: members, roles, invitations and SSH keys.
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme. No path carries a
 * `projectId`, and the current project is the one the token states. Tokens are obtained from the
 * account API.
 *
 * `GET /api/v1/membership` returns the roles and permissions the caller holds in the current
 * project. It does not state whether a given operation is allowed; each service declares which permission its own operations require.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const listPoliciesParamsUserIdMax = 255;

export const ListPoliciesParams = zod.strictObject({
  userId: zod
    .string()
    .max(listPoliciesParamsUserIdMax)
    .optional()
    .describe("Restricts the result to one person. Omitting it covers the whole project"),
});

export type ListPoliciesParams = zod.input<typeof ListPoliciesParams>;
export type ListPoliciesParamsOutput = zod.output<typeof ListPoliciesParams>;
