/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Quote Types
 * Price previews returned before purchase confirmation. Types only; this document declares no operations.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { Money } from "./money.zod.js";
import { QuotedLine } from "./quotedLine.zod.js";

export const Quote = zod
  .strictObject({
    lines: zod
      .array(QuotedLine)
      .describe(
        "One line for each item the purchase would order, in the order it would order them.",
      ),
    subtotal: zod
      .union([Money, zod.null()])
      .describe(
        "Sum of line amounts before discounts, less tax already included in the discounted line\namounts, as on an invoice. Null when any line cannot be priced.",
      ),
    discount_amount: zod
      .union([Money, zod.null()])
      .describe("Sum of line discounts. Null when any line cannot be priced."),
    tax_amount: zod
      .union([Money, zod.null()])
      .describe("Sum of tax on the discounted line amounts. Null when any line cannot be priced."),
    total: zod
      .union([Money, zod.null()])
      .describe(
        "subtotal minus discount_amount plus tax_amount: what checkout collects, before applying\ncredit grants or balance. Equals the sum of line totals and excludes estimated_usage_amount.\nNull when any line cannot be priced.",
      ),
    estimated_usage_amount: zod
      .union([Money, zod.null()])
      .describe(
        "Sum of the lines' estimated_usage_amount. A projection, not part of total and not collected at\ncheckout. Null when no line is billed for usage or when any usage cannot be priced.",
      ),
    currency: zod.string(),
    proration_date: zod.iso
      .datetime({ offset: true })
      .nullable()
      .describe(
        "Changes only; null otherwise. The instant the change is priced from. Pass it with the change so the\norder is priced from the same instant.",
      ),
    refundable_amount: zod
      .union([Money, zod.null()])
      .describe(
        "Changes that lower the price only; null otherwise. What the change would return to the original\npayment sources, including the tax paid on it. total is zero for such a change.",
      ),
  })
  .describe(
    "A price preview for the purchase described by a service, calculated by Billing. Nothing is saved,\ncharged or reserved, and no discount redemption is consumed. Account discounts and tax are\nevaluated as for automatic checkout. Promotion codes are evaluated through Billing quote operations.\nAll amounts use currency. This preview does not lock prices or guarantee discount availability.",
  );

export type Quote = zod.input<typeof Quote>;
export type QuoteOutput = zod.output<typeof Quote>;
