/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Monitoring API
 * Monitoring for your own project: enroll machines, read metrics, work through incidents, schedule maintenance windows, and set availability targets.
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * ## Two distinctions worth keeping straight
 *
 * - **Disabling is not deleting.** `POST /servers/{id}/disable` is reversible and preserves all history. `DELETE /servers/{id}` also removes the monitored host, its history and every incident recorded against it, and cannot be undone.
 * - **Recovery is not closure.** `incident_status` reports whether monitoring considers the problem recovered; `closed_at` reports whether someone has finished handling it. An incident that has not recovered may still be closed as an accepted risk.
 *
 * ## The PSK is returned once
 *
 * Enrollment and rotation responses include `tls_psk`. No other endpoint will return it again, so store it immediately. If it is lost, rotate once more — at the cost of updating the agent configuration on the monitored machine.
 * OpenAPI spec version: 1.0.0
 */
import type { PutStatusPageRequestBodyTheme } from "./putStatusPageRequestBodyTheme.js";

export interface PutStatusPageRequestBody {
  /**
   * #RRGGBB. Applied to the page styling; only a strict six-digit hexadecimal value is accepted
   * @maxLength 7
   * @pattern ^(#[0-9a-fA-F]{6})?$
   */
  brand_color?: string;
  /**
   * Read-only here. Bind a custom domain through PUT /status-page/domain, which verifies ownership first; a value sent here is ignored
   * @maxLength 253
   */
  custom_domain?: string;
  /**
   * The line of free-form text in the page footer. Plain text
   * @maxLength 500
   */
  footer_text?: string;
  /**
   * The line shown below the title
   * @maxLength 255
   */
  headline?: string;
  /** @maxLength 2048 */
  logo_url?: string;
  /**
   * Page title
   * @minLength 1
   * @maxLength 128
   */
  name: string;
  /** While false, the public address returns 404. Unpublished by default */
  published?: boolean;
  /** Not indexed by default. Once a page has been crawled, switching back does not remove copies already held in third-party indexes */
  search_engine_index?: boolean;
  /**
   * An optional readable address segment under the shared domain. Lowercase letters, digits and hyphens; globally unique. Leave it empty and the page is served at /<project id>, which needs no configuration and cannot be taken by anyone else
   * @minLength 1
   * @maxLength 63
   * @pattern ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$
   */
  slug?: string;
  /** @maxLength 2048 */
  support_url?: string;
  theme?: PutStatusPageRequestBodyTheme;
  /**
   * IANA name. Empty selects UTC
   * @maxLength 64
   */
  timezone?: string;
  /**
   * @minimum 30
   * @maximum 365
   */
  uptime_days?: number;
  /**
   * The text shown on the support link. Empty uses the page default. Different products call this different things — help centre, submit a ticket, support
   * @maxLength 32
   */
  support_label?: string;
}
