/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Monitoring API
 * Monitoring for your own project: enroll machines, read metrics, work through incidents, schedule maintenance windows, and set availability targets.
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * ## Two distinctions worth keeping straight
 *
 * - **Disabling is not deleting.** `POST /servers/{id}/disable` is reversible and preserves all history. `DELETE /servers/{id}` also removes the monitored host, its history and every incident recorded against it, and cannot be undone.
 * - **Recovery is not closure.** `incident_status` reports whether monitoring considers the problem recovered; `closed_at` reports whether someone has finished handling it. An incident that has not recovered may still be closed as an accepted risk.
 *
 * ## The PSK is returned once
 *
 * Enrollment and rotation responses include `tls_psk`. No other endpoint will return it again, so store it immediately. If it is lost, rotate once more — at the cost of updating the agent configuration on the monitored machine.
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduleWindowResource } from "./scheduleWindowResource.js";
import type { SLOResourceMinSeverity } from "./sLOResourceMinSeverity.js";
import type { SLOResourcePeriod } from "./sLOResourcePeriod.js";
import type { SLOResourceSyncStatus } from "./sLOResourceSyncStatus.js";

export interface SLOResource {
  effective_from: string;
  last_error: string;
  min_severity: SLOResourceMinSeverity;
  name: string;
  period: SLOResourcePeriod;
  project_id: string;
  /**
   * Empty means a 24x7 commitment
   * @nullable
   */
  schedule: ScheduleWindowResource[] | null;
  slo_id: string;
  /** Target availability, such as 99.9 */
  slo_percent: number;
  sync_status: SLOResourceSyncStatus;
  timezone: string;
}
