/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Monitoring API
 * Monitoring for your own project: enroll machines, read metrics, work through incidents, schedule maintenance windows, and set availability targets.
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * ## Two distinctions worth keeping straight
 *
 * - **Disabling is not deleting.** `POST /servers/{id}/disable` is reversible and preserves all history. `DELETE /servers/{id}` also removes the monitored host, its history and every incident recorded against it, and cannot be undone.
 * - **Recovery is not closure.** `incident_status` reports whether monitoring considers the problem recovered; `closed_at` reports whether someone has finished handling it. An incident that has not recovered may still be closed as an accepted risk.
 *
 * ## The PSK is returned once
 *
 * Enrollment and rotation responses include `tls_psk`. No other endpoint will return it again, so store it immediately. If it is lost, rotate once more — at the cost of updating the agent configuration on the monitored machine.
 * OpenAPI spec version: 1.0.0
 */
import type { StatusPageMaintenanceComponentResource } from "./statusPageMaintenanceComponentResource.js";
import type { StatusPageMaintenanceResourceMaintenanceStatus } from "./statusPageMaintenanceResourceMaintenanceStatus.js";

export interface StatusPageMaintenanceResource {
  /** @nullable */
  affected_components: StatusPageMaintenanceComponentResource[] | null;
  /** Maintenance description. Plain text */
  body: string;
  /**
   * When the maintenance actually finished
   * @nullable
   */
  completed_at: string | null;
  maintenance_id: string;
  maintenance_status: StatusPageMaintenanceResourceMaintenanceStatus;
  name: string;
  scheduled_for: string;
  scheduled_until: string;
  /**
   * When the maintenance actually started, which may differ from the scheduled time
   * @nullable
   */
  started_at: string | null;
}
