/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Catalog API
 * What the platform sells and what it costs: services, sellable plans, prices, shared rate
 * cards and estimates. No credentials are required.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ListPricesHeaders = zod.strictObject({
  "If-None-Match": zod.string().optional(),
});

export type ListPricesHeaders = zod.input<typeof ListPricesHeaders>;
export type ListPricesHeadersOutput = zod.output<typeof ListPricesHeaders>;
