/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Catalog API
 * What the platform sells and what it costs: services, sellable plans, prices, shared rate
 * cards and estimates. No credentials are required.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { ProductID } from "./productID.zod.js";

export const listPricesParamsPageMax = 2147483647;

export const listPricesParamsPageSizeMax = 100;

export const listPricesParamsCurrencyMin = 3;
export const listPricesParamsCurrencyMax = 3;

export const ListPricesParams = zod.strictObject({
  page: zod.int().min(1).max(listPricesParamsPageMax).optional(),
  page_size: zod.int().min(1).max(listPricesParamsPageSizeMax).optional(),
  currency: zod.string().min(listPricesParamsCurrencyMin).max(listPricesParamsCurrencyMax),
  product_id: ProductID.optional(),
  type: zod.enum(["postpaid", "prepaid", "one_time"]).optional(),
});

export type ListPricesParams = zod.input<typeof ListPricesParams>;
export type ListPricesParamsOutput = zod.output<typeof ListPricesParams>;
