/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Catalog API
 * What the platform sells and what it costs: services, sellable plans, prices, shared rate
 * cards and estimates. No credentials are required.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const listPricesByPlanParamsPageMax = 2147483647;

export const listPricesByPlanParamsPageSizeMax = 100;

export const ListPricesByPlanParams = zod.strictObject({
  page: zod.int().min(1).max(listPricesByPlanParamsPageMax).optional(),
  page_size: zod.int().min(1).max(listPricesByPlanParamsPageSizeMax).optional(),
  currency: zod.string().optional(),
});

export type ListPricesByPlanParams = zod.input<typeof ListPricesByPlanParams>;
export type ListPricesByPlanParamsOutput = zod.output<typeof ListPricesByPlanParams>;
