/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Catalog API
 * What the platform sells and what it costs: services, sellable plans, prices, shared rate
 * cards and estimates. No credentials are required.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { ObjectIdentity } from "./objectIdentity.zod.js";

export const PlanFeature = zod.strictObject({
  feature: ObjectIdentity,
  name: zod.string(),
});

export type PlanFeature = zod.input<typeof PlanFeature>;
export type PlanFeatureOutput = zod.output<typeof PlanFeature>;
