/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Catalog API
 * What the platform sells and what it costs: services, sellable plans, prices, shared rate
 * cards and estimates. No credentials are required.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ProductIDMax = 64;

export const ProductIDRegExp = new RegExp("^[a-z][a-z0-9]*(-[a-z0-9]+)*$");

export const ProductID = zod
  .string()
  .min(1)
  .max(ProductIDMax)
  .regex(ProductIDRegExp)
  .describe("Immutable platform service identifier, such as compute, canopy or assistant.");

export type ProductID = zod.input<typeof ProductID>;
export type ProductIDOutput = zod.output<typeof ProductID>;
