/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Notification API
 * Read the notifications this platform has sent you, and choose where each kind of notification
 * is delivered.
 *
 * Every service on the platform reports events here rather than contacting you directly. This
 * API is the single place where those events are read, and the single place where delivery is
 * configured.
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * **Neither the path nor the headers carry a `project_id`**: the current project is determined by
 * the token. Listing operations return everything addressed to you across every project by
 * default, because a notification is addressed to a person rather than to a project; pass
 * `scope=current_project` to narrow the result to the project in the token.
 *
 * ## Conventions
 *
 * - **Notifications are typed, and the type determines who receives it.** A type such as
 *   `compute.instance.provisioned` is addressed to whoever created the instance, while
 *   `monitoring.alert.raised` is addressed to every member of the project. The full catalogue is
 *   available from `GET /api/v1/notification-types` and is stable: a type identifier is never
 *   reused for a different event.
 * - **Text is rendered at read time from the language on your preferences.** Changing the
 *   language changes the text of everything already in the inbox. Messages already delivered by
 *   email or to an outbound channel are not rewritten, because they have already been sent.
 * - **Times inside rendered text are stated in UTC and say so.** There is no time zone setting.
 *   Clients that can determine the reader's time zone should present `created_at`, `occurred_at`
 *   and the timestamps in `params` — all of which are RFC 3339 — in local time instead. Email
 *   cannot do this, which is why the text it carries is explicit about being UTC.
 * - **Some types must reach you, and those cannot be muted or removed from email.** They are
 *   marked `mandatory` in the catalogue: types you would only find out about by signing in, when
 *   not finding out costs you something — a suspension, a deletion, a credential that expires.
 *   Everything else about them is still configurable, including adding channels of your own.
 * - **Deleting a preference restores the default; it does not turn the type off.** To stop
 *   receiving a type, set `muted` on it.
 * - **Outbound channels deliver nothing until they are verified.** Registering a channel does not
 *   contact it. Verification is a separate operation that sends one message, and only a channel
 *   that has acknowledged it receives anything afterwards.
 * - **Channel endpoints are never returned.** No operation, including the one that registers
 *   them, returns the address that was submitted. A channel entered incorrectly must be deleted
 *   and registered again.
 *
 * ## Rate and volume
 *
 * Delivery to outbound channels is limited per channel, and bursts of alerts about one server are
 * summarised rather than sent individually. Nothing is summarised in the inbox: it always holds
 * every notification. A notification that was summarised or suppressed is still readable here.
 *
 * ## One-time credentials
 *
 * Some notifications carry a reference to a credential rather than the credential itself — the
 * initial password of a newly created instance, for example. That credential is readable exactly
 * once, expires on its own, and is destroyed as soon as it has been read. Requesting it a second
 * time returns `CREDENTIAL_TICKET_CONSUMED`.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { ChannelKind } from "./channelKind.zod.js";
import { ChannelScope } from "./channelScope.zod.js";

export const ChannelResource = zod
  .strictObject({
    channel_scope: ChannelScope,
    consecutive_failures: zod
      .int()
      .describe(
        "Deliveries that have failed in a row. Reset by a success, and by re-enabling the channel",
      ),
    created_at: zod.iso.datetime({ offset: true }),
    disabled_at: zod.iso
      .datetime({ offset: true })
      .nullable()
      .describe("When the channel was disabled after repeated failures; null if it is enabled"),
    disabled_reason: zod.string().nullable().describe("Why it was disabled; null if it is enabled"),
    id: zod.uuid(),
    kind: ChannelKind,
    last_error: zod
      .string()
      .nullable()
      .describe(
        "Why the most recent attempt failed, in the endpoint's own wording; null if the most recent attempt succeeded",
      ),
    last_failure_at: zod.iso.datetime({ offset: true }).nullable(),
    last_success_at: zod.iso.datetime({ offset: true }).nullable(),
    name: zod.string(),
    project_id: zod
      .uuid()
      .nullable()
      .describe("The project this channel is shared with; null for a channel of scope user"),
    redacted: zod
      .string()
      .describe("A partially masked fragment of the endpoint, for visual identification only"),
    updated_at: zod.iso.datetime({ offset: true }),
    verified_at: zod.iso
      .datetime({ offset: true })
      .nullable()
      .describe(
        "When the endpoint last acknowledged a verification message; null while it never has, during which the channel is skipped",
      ),
  })
  .describe("A registered outbound channel. The endpoint itself is never included.");

export type ChannelResource = zod.input<typeof ChannelResource>;
export type ChannelResourceOutput = zod.output<typeof ChannelResource>;
