/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Account API
 * Everything that comes before a project is chosen: registration, the account itself, the projects the caller belongs to, and entry into one of them.
 *
 * ## Authentication
 *
 * Every request carries `Authorization: Bearer <access token>`, obtained by signing in at auth.leaflow.net. The endpoints that need no token say so.
 *
 * ## Entering a project
 *
 * 1. `GET /account/v1/projects` lists the projects the caller belongs to. The first call registers the account, taking the name and email address from the sign-in claims.
 * 2. `POST /account/v1/projects/{projectId}/scoped-tokens` returns a scoped token for the project chosen.
 * 3. Every other service is called with that scoped token.
 *
 * A scoped token cannot be renewed. Repeat step 2 for a new one, and sign in again at auth.leaflow.net once the access token itself has expired.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { InvitationResource } from "./invitationResource.zod.js";

export const LengthAwarePageInvitationResource = zod.strictObject({
  items: zod.array(InvitationResource).describe("The items in this page"),
  limit: zod.int().describe("Maximum number of items in this page, echoing the request"),
  offset: zod.int().describe("Number of items skipped, echoing the request"),
  total: zod.int().describe("Total number of matches, not only this page"),
});

export type LengthAwarePageInvitationResource = zod.input<typeof LengthAwarePageInvitationResource>;
export type LengthAwarePageInvitationResourceOutput = zod.output<
  typeof LengthAwarePageInvitationResource
>;
