/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Account API
 * Everything that comes before a project is chosen: registration, the account itself, the projects the caller belongs to, and entry into one of them.
 *
 * ## Authentication
 *
 * Every request carries `Authorization: Bearer <access token>`, obtained by signing in at auth.leaflow.net. The endpoints that need no token say so.
 *
 * ## Entering a project
 *
 * 1. `GET /account/v1/projects` lists the projects the caller belongs to. The first call registers the account, taking the name and email address from the sign-in claims.
 * 2. `POST /account/v1/projects/{projectId}/scoped-tokens` returns a scoped token for the project chosen.
 * 3. Every other service is called with that scoped token.
 *
 * A scoped token cannot be renewed. Repeat step 2 for a new one, and sign in again at auth.leaflow.net once the access token itself has expired.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { GrantResource } from "./grantResource.zod.js";
import { ProjectResource } from "./projectResource.zod.js";

export const ScopedTokenResponseBody = zod.strictObject({
  expires_at: zod.iso
    .datetime({ offset: true })
    .describe(
      "When the token expires. Exchange for a new one before then rather than waiting for the first 401",
    ),
  expires_in: zod.int().describe("Seconds remaining before expiry"),
  grant: GrantResource.describe(
    "**A snapshot taken at the moment of the exchange. It is not carried in the token, and must not be cached.** It serves to render what a user may do; each request is decided again",
  ),
  project: ProjectResource.describe(
    "The project itself, so that no further lookup is needed after the exchange",
  ),
  token: zod.string().describe("The scoped token, to be sent as `Authorization: Bearer`"),
  token_type: zod.string().describe("Always `Bearer`"),
});

export type ScopedTokenResponseBody = zod.input<typeof ScopedTokenResponseBody>;
export type ScopedTokenResponseBodyOutput = zod.output<typeof ScopedTokenResponseBody>;
