/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow DNS API
 * Manage DNS records across supported providers through a single API. Register a provider
 * credential, and every domain that credential can reach becomes readable and writable here.
 *
 * Reads and writes always reflect the current state at the provider. Records changed through the
 * provider's own console, an ACME client, or any other automation are visible here immediately,
 * and changes made here take effect there.
 *
 * ## Authentication
 *
 * Every request carries a scoped token; see the `bearerAuth` security scheme.
 *
 * **Neither the path nor the headers carry a `project_id`**: the current project is determined by
 * the token.
 *
 * ## Conventions
 *
 * - **Records are addressed as record sets, not as individual records.** All records sharing a
 *   name and a type form one set — for example, three A records pointing at three addresses. This
 *   API exposes no per-record identifier, because provider-assigned identifiers are neither
 *   portable across providers nor guaranteed to be stable within one.
 * - **`PUT` replaces an entire record set; `PATCH` names individual values.** See below; this is
 *   the single most consequential distinction in this API.
 * - **Confirm which credential owns a domain before writing to it.** The same domain can exist in
 *   more than one provider account — most commonly while a domain is being migrated and the old
 *   account still holds it — and only one of them is actually serving queries.
 * - **Changes do not take effect everywhere at once.** A write reaches the provider immediately,
 *   but resolvers elsewhere continue serving the previous value until its TTL expires. Allow at
 *   least one TTL before verifying a change by resolving the name.
 * - **Credential material is never returned.** No operation, including the one that registers it,
 *   returns the values that were submitted. A credential that was entered incorrectly must be
 *   deleted and registered again.
 *
 * ## PUT or PATCH
 *
 * `PUT` states what a record set should contain. `PATCH` names values to add or remove and leaves
 * the rest alone. The distinction is concurrency.
 *
 * Changing part of a set with `PUT` means reading it and submitting a modified list. That is a
 * read-modify-write: a value added in between — by a concurrent certificate issuance, by another
 * automation, or from the provider's own console — is absent from the submitted list and is
 * therefore removed. Every request in that sequence returns 2xx.
 *
 * `PATCH` reads nothing. It is the only operation on a record set safe to issue concurrently, and
 * the one certificate issuance must use.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { RecordType } from "./recordType.zod.js";

export const RecordSetResource = zod
  .strictObject({
    name: zod.string().describe("The name relative to the domain. `@` denotes the domain itself"),
    ttl: zod.int().describe("Time to live, in seconds. 0 leaves the choice to the provider"),
    type: RecordType,
    values: zod
      .array(zod.string())
      .describe(
        'Every value in this record set, in unescaped zone-file RDATA syntax:\n\n- `A`, `AAAA`: `192.0.2.1`, `2001:db8::1`\n- `CNAME`, `NS`: `target.example.com.`, absolute, with a trailing dot\n- `TXT`: the text itself, neither quoted nor escaped\n- `MX`: `10 mail.example.com.`\n- `SRV`: `10 20 443 target.example.com.`\n- `CAA`: `0 issue "letsencrypt.org"`',
      ),
    zone: zod.string().describe("The domain in absolute form, with a trailing dot"),
  })
  .describe("Every record sharing a name and a type.");

export type RecordSetResource = zod.input<typeof RecordSetResource>;
export type RecordSetResourceOutput = zod.output<typeof RecordSetResource>;
