/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const AccountIdentity = zod.strictObject({
  id: zod.int(),
  name: zod.string(),
  currency: zod.string(),
});

export type AccountIdentity = zod.input<typeof AccountIdentity>;
export type AccountIdentityOutput = zod.output<typeof AccountIdentity>;
