/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { Allowance } from "./allowance.zod.js";
import { OffsetPagination } from "./offsetPagination.zod.js";

export const AllowanceList = zod.strictObject({
  items: zod.array(Allowance),
  pagination: OffsetPagination,
});

export type AllowanceList = zod.input<typeof AllowanceList>;
export type AllowanceListOutput = zod.output<typeof AllowanceList>;
