/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ApplicablePlan = zod
  .strictObject({
    id: zod.uuid(),
    name: zod.string(),
    active: zod.boolean(),
  })
  .describe(
    "A plan it refers to. active is false once the plan is archived; it still applies to subscriptions already on this plan.",
  );

export type ApplicablePlan = zod.input<typeof ApplicablePlan>;
export type ApplicablePlanOutput = zod.output<typeof ApplicablePlan>;
