/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const billingAccountUpdateNameMax = 255;

export const billingAccountUpdateLegalNameMax = 255;

export const billingAccountUpdateEmailMax = 255;

export const billingAccountUpdateAddressLine1Max = 255;

export const billingAccountUpdateAddressLine2Max = 255;

export const billingAccountUpdateAddressCityMax = 128;

export const billingAccountUpdateAddressStateMax = 128;

export const billingAccountUpdateAddressPostalCodeMax = 32;

export const billingAccountUpdateAddressCountryMin = 2;
export const billingAccountUpdateAddressCountryMax = 2;

export const billingAccountUpdateTaxIdMax = 64;

export const BillingAccountUpdate = zod.strictObject({
  name: zod.string().max(billingAccountUpdateNameMax).optional(),
  legal_name: zod.string().max(billingAccountUpdateLegalNameMax).optional(),
  email: zod.string().max(billingAccountUpdateEmailMax).optional(),
  address_line1: zod.string().max(billingAccountUpdateAddressLine1Max).optional(),
  address_line2: zod.string().max(billingAccountUpdateAddressLine2Max).optional(),
  address_city: zod.string().max(billingAccountUpdateAddressCityMax).optional(),
  address_state: zod.string().max(billingAccountUpdateAddressStateMax).optional(),
  address_postal_code: zod.string().max(billingAccountUpdateAddressPostalCodeMax).optional(),
  address_country: zod
    .string()
    .min(billingAccountUpdateAddressCountryMin)
    .max(billingAccountUpdateAddressCountryMax)
    .optional(),
  tax_id: zod.string().max(billingAccountUpdateTaxIdMax).optional(),
});

export type BillingAccountUpdate = zod.input<typeof BillingAccountUpdate>;
export type BillingAccountUpdateOutput = zod.output<typeof BillingAccountUpdate>;
