/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const listPaymentOptionsParamsPageMax = 2147483647;

export const listPaymentOptionsParamsPageSizeMax = 100;

export const ListPaymentOptionsParams = zod.strictObject({
  page: zod.int().min(1).max(listPaymentOptionsParamsPageMax).optional(),
  page_size: zod.int().min(1).max(listPaymentOptionsParamsPageSizeMax).optional(),
});

export type ListPaymentOptionsParams = zod.input<typeof ListPaymentOptionsParams>;
export type ListPaymentOptionsParamsOutput = zod.output<typeof ListPaymentOptionsParams>;
