/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const OrderStatus = zod
  .enum([
    "pending_checkout",
    "pending",
    "active",
    "completed",
    "partially_completed",
    "failed",
    "canceled",
  ])
  .describe(
    "pending_checkout has recorded purchase terms but no confirmed checkout; only a deferred order\nwith an amount due reaches it, since a zero-total order completes checkout at placement.\nConfirmation moves it to pending. Both pending_checkout\nand pending can expire or be canceled; neither establishes service delivery.\n\nFollows the items. `pending` has confirmed checkout, is not yet accepted and may be paid or unpaid. `active` is\naccepted with items still being set up. `completed` means every item was set up.\n`partially_completed` means some items were set up and the others failed and were\nrefunded to their original payment sources. `failed` means every item failed and the\nwhole order was refunded. `canceled` means the order was withdrawn before payment and\nnothing was charged.",
  );

export type OrderStatus = zod.input<typeof OrderStatus>;
export type OrderStatusOutput = zod.output<typeof OrderStatus>;
