/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const PaidWith = zod
  .strictObject({
    method_type: zod
      .string()
      .describe(
        "`balance` when the account's balance and credits covered it in full. Otherwise the method used\nwith the gateway, such as `card`.",
      ),
    payment_gateway: zod
      .string()
      .optional()
      .describe("The gateway that collected it. Absent when `method_type` is `balance`."),
    payment_method_id: zod
      .uuid()
      .optional()
      .describe("The saved payment method that was charged, when one was."),
    brand: zod.string().optional(),
    last4: zod.string().optional(),
  })
  .describe(
    "How it was paid, as recorded at the time. It is kept as it was: removing the card afterwards\ndoes not change it, and `payment_method_id` may then name a card that no longer exists.",
  );

export type PaidWith = zod.input<typeof PaidWith>;
export type PaidWithOutput = zod.output<typeof PaidWith>;
