/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { PaymentOptionMethod } from "./paymentOptionMethod.zod.js";

export const PaymentOption = zod
  .strictObject({
    payment_gateway: zod.string().describe("The value to send as `payment_gateway`."),
    methods: zod.array(PaymentOptionMethod),
  })
  .describe(
    "A payment gateway that accepts payment in the account's currency, with the methods it accepts.",
  );

export type PaymentOption = zod.input<typeof PaymentOption>;
export type PaymentOptionOutput = zod.output<typeof PaymentOption>;
