/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const paymentMethodSetupPaymentGatewayMax = 32;

export const PaymentMethodSetup = zod.strictObject({
  payment_gateway: zod
    .string()
    .min(1)
    .max(paymentMethodSetupPaymentGatewayMax)
    .describe("The selected gateway supporting saved payment methods."),
  billing_account_id: zod.int(),
});

export type PaymentMethodSetup = zod.input<typeof PaymentMethodSetup>;
export type PaymentMethodSetupOutput = zod.output<typeof PaymentMethodSetup>;
