/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const PaymentOptionMethod = zod.strictObject({
  method_type: zod
    .string()
    .describe("The value to send as `method_type`, such as card, wechat_pay or alipay."),
  reusable: zod
    .boolean()
    .describe(
      "Whether a method of this type can be saved with create-payment-method-setup and charged later\nwithout the customer present. Methods that are not reusable are paid anew each time.",
    ),
});

export type PaymentOptionMethod = zod.input<typeof PaymentOptionMethod>;
export type PaymentOptionMethodOutput = zod.output<typeof PaymentOptionMethod>;
