/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const PaymentCancellationReason = zod
  .enum(["abandoned", "requested_by_customer"])
  .describe(
    "Why a gateway payment was withdrawn. `abandoned` means the customer did not complete it within the time\nallowed for payment. `requested_by_customer` means the customer canceled it.",
  );

export type PaymentCancellationReason = zod.input<typeof PaymentCancellationReason>;
export type PaymentCancellationReasonOutput = zod.output<typeof PaymentCancellationReason>;
