/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { OffsetPagination } from "./offsetPagination.zod.js";
import { RenewalPrice } from "./renewalPrice.zod.js";

export const RenewalPriceList = zod.strictObject({
  items: zod.array(RenewalPrice),
  pagination: OffsetPagination,
});

export type RenewalPriceList = zod.input<typeof RenewalPriceList>;
export type RenewalPriceListOutput = zod.output<typeof RenewalPriceList>;
