/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { AccountIdentity } from "./accountIdentity.zod.js";
import { CancellationRequest } from "./cancellationRequest.zod.js";
import { NamedIdentity } from "./namedIdentity.zod.js";
import { ObjectIdentity } from "./objectIdentity.zod.js";
import { PaidWith } from "./paidWith.zod.js";
import { Product } from "./product.zod.js";
import { ProductID } from "./productID.zod.js";
import { RefundPolicy } from "./refundPolicy.zod.js";
import { TerminationPolicy } from "./terminationPolicy.zod.js";

export const subscriptionDiscountedRenewalsRemainingMin = 0;

export const Subscription = zod
  .strictObject({
    currency: zod.string(),
    billing_type: zod.enum(["postpaid", "prepaid", "one_time"]),
    interval: zod.enum(["none", "day", "month", "year"]),
    interval_count: zod.int().min(1).optional(),
    recurring_amount: zod
      .string()
      .optional()
      .describe(
        "Whole-subscription prepaid renewal amount, after continuing discounts and before tax.\nPending subscriptions show base terms until checkout confirms any new continuing discount.\nAbsent for other billing types.",
      ),
    termination_policy: TerminationPolicy.optional(),
    refund_policy: RefundPolicy.optional(),
    order_item_id: zod.uuid().optional(),
    replaces_subscription_id: zod
      .uuid()
      .optional()
      .describe(
        "Present only on subscriptions created by an earlier change that replaced the subscription. A change now keeps the subscription ID.",
      ),
    coupon_id: zod.uuid().optional(),
    coupon: ObjectIdentity.optional(),
    discounted_renewals_remaining: zod
      .int()
      .min(subscriptionDiscountedRenewalsRemainingMin)
      .optional(),
    suspend_reason: zod.string().optional(),
    billing_cycle_anchor: zod.iso.datetime({ offset: true }).optional(),
    cancellation_request: CancellationRequest.optional(),
    paid_with: PaidWith.optional().describe(
      "How the purchase, or the latest renewal paid with a saved card, was paid. Automatic renewal\ntries this card after the account's balance and credits, and the account's default card after\nthat.",
    ),
    created_at: zod.iso.datetime({ offset: true }).optional(),
    id: zod.uuid(),
    billing_account_id: zod
      .int()
      .describe(
        "The billing account that made the purchase. Renewals of a project subscription are charged to the project's current billing account.",
      ),
    account: AccountIdentity,
    product_id: ProductID,
    project_id: zod
      .uuid()
      .nullish()
      .describe(
        "Which project this is for. Absent when it was bought at account level, such as a\nmembership, which belongs to no single project.",
      ),
    project: zod
      .union([NamedIdentity, zod.null()])
      .optional()
      .describe(
        "The project and its current name, for display. Absent for a purchase at account level,\nand when the project no longer exists or its details cannot be read at the moment;\n`project_id` still identifies it then.",
      ),
    product: Product,
    plan_id: zod.uuid(),
    plan_name: zod.string(),
    price_id: zod.uuid(),
    quantity: zod.string(),
    paid_until: zod.iso
      .datetime({ offset: true })
      .nullish()
      .describe(
        "End of the prepaid service already activated. Null until a new subscription becomes active,\neven when its purchase has been paid, and for postpaid subscriptions with no prepaid end date.",
      ),
    auto_renew: zod.boolean(),
    status: zod
      .enum(["pending", "provisioning", "active", "suspended", "canceled", "terminated"])
      .describe(
        "pending means the purchase relationship exists but its order has not been accepted.\nprovisioning means the service accepted the order and is delivering. For a service-owned\npurchase, only confirmed delivery moves it to active; paying alone does not.",
      ),
    started_at: zod.iso
      .datetime({ offset: true })
      .nullish()
      .describe(
        "Confirmed start of service. Null until a new subscription becomes active, including after payment.",
      ),
    ended_at: zod.iso.datetime({ offset: true }).nullish(),
  })
  .describe(
    "An independently billed purchase relationship, separate from the owning service's resource.\nPlacing a new prepaid or postpaid service order creates a pending subscription for each line\nin the same purchase transaction. Its ID is returned on the order item and remains stable\nthrough checkout and delivery. One order may create several subscriptions, such as an instance,\nits system disk and its address; it has no single subscription ID.\n\nPending and provisioning do not grant service or accrue usage. A service-owned subscription\nbecomes provisioning when the owning service accepts the order, and active when the service\nconfirms delivery, with started_at set to the confirmed effective time; payment changes neither. Prepaid service periods start\nthen; postpaid usage starts only when the service reports actual delivery and metering.\n\nOne-time delivery may omit a subscription. Renewals reference and extend existing subscriptions\nrather than creating another; a change keeps the subscription ID and switches its terms when it\ntakes effect. Canceling or failing an\nunfulfilled purchase closes its pending or provisioning subscriptions without starting a service period.\nFixed renewals use the agreed recurring_amount and interval; already paid periods retain their\noriginal value. Technical state belongs to the owning service.\n\nA purchased shared capacity limit, such as a regional snapshot count quota, can have its own\nsubscription. Activating that capacity confirms delivery of the quota, not individual snapshots.\nCreating or deleting snapshots within it does not create, activate or terminate more subscriptions;\nthe owning service enforces current holdings against the purchased count.",
  );

export type Subscription = zod.input<typeof Subscription>;
export type SubscriptionOutput = zod.output<typeof Subscription>;
