/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const TerminationPolicy = zod
  .enum(["immediate", "period_end"])
  .describe(
    "Whether a fulfilled purchase may end immediately or only after its paid term. Does not grant a refund. When absent, the terms are not configured and termination requires review.",
  );

export type TerminationPolicy = zod.input<typeof TerminationPolicy>;
export type TerminationPolicyOutput = zod.output<typeof TerminationPolicy>;
