/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Leaflow Billing Account API
 * The caller's billing accounts, purchases and payments.
 * Query accepted financial operations by their original IDs after an unknown outcome.
 * Public prices and estimates are served under `/catalog/v1/` and require no credentials.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";
import { OffsetPagination } from "./offsetPagination.zod.js";
import { Transaction } from "./transaction.zod.js";

export const TransactionList = zod.strictObject({
  items: zod.array(Transaction),
  pagination: OffsetPagination,
});

export type TransactionList = zod.input<typeof TransactionList>;
export type TransactionListOutput = zod.output<typeof TransactionList>;
